// Code generated by api-codegen; DO NOT EDIT.

package cmd

import (
	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newBiContainersCmd())
}

func newBiContainersCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "bi-containers",
		Short: "Bi containers",
	}
	cmd.AddCommand(newBiContainersCreateCmd())
	cmd.AddCommand(newBiContainersDeleteCmd())
	cmd.AddCommand(newBiContainersGetCmd())
	cmd.AddCommand(newBiContainersListCmd())
	cmd.AddCommand(newBiContainersUpdateCmd())
	return cmd
}

func newBiContainersCreateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a BI container",
		Long:  "Create an empty BI container.\n\nThe container holds no connections until you add some. Its type is fixed at creation and\ndecides which connections it accepts. A `looker` container takes both the Looker API\nconnection and the LookML git connection. The deployment has to be one the deployments\nlist returns; any other id returns 404. A deployment that does not support the BI tool,\nor needs an upgrade first, returns 409.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.BiContainersAPI.CreateBiContainer(ctx)
			typeValue, err := flagString(cmd, "type")
			if err != nil {
				return err
			}
			type_, err := sdk.NewNewBiContainerTypeFromValue(typeValue)
			if err != nil {
				return err
			}
			name, err := flagString(cmd, "name")
			if err != nil {
				return err
			}
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			body := sdk.NewBiContainerIn(*type_, name, deploymentId)
			req = req.BiContainerIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "type", "name", "deployment_id", "deployment_name", "created_time")
		},
	}
	cmd.Flags().String("type", "", "The BI tool the container represents. Every connection added to it has to be for this tool. Cannot be changed after the container is created.")
	_ = cmd.RegisterFlagCompletionFunc("type", enumCompletion(sdk.AllowedNewBiContainerTypeEnumValues))
	_ = cmd.MarkFlagRequired("type")
	cmd.Flags().String("name", "", "Display name for the BI container.")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().String("deployment-id", "", "The deployment the container's connections will run through. Pick one from the deployments list. Only a deployment on Monte Carlo's current collection platform is accepted.")
	_ = cmd.MarkFlagRequired("deployment-id")
	return cmd
}

func newBiContainersDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <bi_container_id>",
		Short: "Delete a BI container",
		Long:  "Delete a BI container.\n\nOnly an empty container can be deleted. Connections are managed as their own resources\nand are never deleted with a container, so remove them first. Deleting the container also\nremoves the BI assets, such as dashboards and reports, collected through it.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete bi container"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.BiContainersAPI.DeleteBiContainer(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newBiContainersGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <bi_container_id>",
		Short: "Get a BI container",
		Long:  "Get one BI container.\n\nAn id that does not exist or belongs to another account returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.BiContainersAPI.GetBiContainer(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "type", "name", "deployment_id", "deployment_name", "created_time")
		},
	}
	return cmd
}

func newBiContainersListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List BI containers",
		Long:  "List every BI container in your account, oldest first.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.BiContainersAPI.ListBiContainers(ctx)
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderList(cmd, out, []string{"id", "name", "type", "deployment_name"})
		},
	}
	return cmd
}

func newBiContainersUpdateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update <bi_container_id>",
		Short: "Update a BI container",
		Long:  "Rename a BI container.\n\nThe name is the only thing you can change. The type and the deployment are fixed when the\ncontainer is created. Sending an empty body leaves the container as it is and returns it.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.BiContainersAPI.UpdateBiContainer(ctx, args[0])
			body := sdk.NewBiContainerPatch()
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.BiContainerPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "type", "name", "deployment_id", "deployment_name", "created_time")
		},
	}
	cmd.Flags().String("name", "", "New display name for the BI container. Omit it to leave the name unchanged. An explicit null is ignored, the same as omitting the field.")
	return cmd
}
