// Code generated by api-codegen; DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newCollectionAgentsCmd())
}

func newCollectionAgentsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "collection-agents",
		Short: "Collection agents",
	}
	cmd.AddCommand(newCollectionAgentsCreateCmd())
	cmd.AddCommand(newCollectionAgentsDeleteCmd())
	cmd.AddCommand(newCollectionAgentsGetCmd())
	cmd.AddCommand(newCollectionAgentsListCmd())
	cmd.AddCommand(newCollectionAgentsRegisterCmd())
	cmd.AddCommand(newCollectionAgentsUpdateCmd())
	return cmd
}

func newCollectionAgentsCreateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create collection agent",
	}
	cmd.AddCommand(newCollectionAgentsCreateGenericOauthClientCmd())
	cmd.AddCommand(newCollectionAgentsCreateGenericTokenCmd())
	return cmd
}

func newCollectionAgentsCreateGenericOauthClientCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic-oauth-client",
		Short: "Create an OAuth client for a generic collection agent",
		Long:  "Create an OAuth 2.0 client for a deployment's generic collection agent.\n\nThe agent presents the client id and secret as `client_id` and `client_secret`, and\nexchanges them for short-lived access tokens on its own. The secret is returned by this\ncall and never again, so store it where the agent will read it. A deployment can hold any\nnumber of clients, so create the next one before deleting the last when rotating.\n\nThe deployment must have been provisioned for a generic collection agent. It does not have\nto be registered yet; creating a credential is what comes before running the agent.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.CreateGenericCollectionAgentOauthClient(ctx)
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			body := sdk.NewGenericCollectionAgentOAuthClientIn(deploymentId)
			if changed(cmd, "description") {
				description, err := flagString(cmd, "description")
				if err != nil {
					return err
				}
				body.SetDescription(description)
			}
			if changed(cmd, "expiration-days") {
				expirationDays, err := flagInt(cmd, "expiration-days")
				if err != nil {
					return err
				}
				body.SetExpirationDays(expirationDays)
			}
			req = req.GenericCollectionAgentOAuthClientIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "client_id", "client_secret", "created_time", "deployment_id", "description", "expiration_time", "id", "scopes", "secret_id", "type")
		},
	}
	cmd.Flags().String("deployment-id", "", "Deployment whose generic collection agent will present this credential. It must have been provisioned for a generic collection agent.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("description", "", "What this credential is for. Monte Carlo generates one naming the agent if you leave it out.")
	cmd.Flags().Int32("expiration-days", 0, "Days until the client stops being accepted. Leave it out for a client that does not expire.")
	return cmd
}

func newCollectionAgentsCreateGenericTokenCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic-token",
		Short: "Create a token for a generic collection agent",
		Long:  "Create a key and secret for a deployment's generic collection agent.\n\nThe agent presents them as `mcd_id` and `mcd_token`. The secret is returned by this call\nand never again, so store it where the agent will read it. A deployment can hold any number\nof tokens, so create the next one before deleting the last when rotating.\n\nThe deployment must have been provisioned for a generic collection agent. It does not have\nto be registered yet; creating a credential is what comes before running the agent.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.CreateGenericCollectionAgentToken(ctx)
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			body := sdk.NewGenericCollectionAgentTokenIn(deploymentId)
			if changed(cmd, "description") {
				description, err := flagString(cmd, "description")
				if err != nil {
					return err
				}
				body.SetDescription(description)
			}
			req = req.GenericCollectionAgentTokenIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "created_time", "deployment_id", "description", "id", "mcd_id", "mcd_token", "type")
		},
	}
	cmd.Flags().String("deployment-id", "", "Deployment whose generic collection agent will present this credential. It must have been provisioned for a generic collection agent.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("description", "", "What this credential is for. Monte Carlo generates one naming the agent if you leave it out.")
	return cmd
}

func newCollectionAgentsDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete collection agent",
	}
	cmd.AddCommand(newCollectionAgentsDeleteAwsCmd())
	cmd.AddCommand(newCollectionAgentsDeleteAzureCmd())
	cmd.AddCommand(newCollectionAgentsDeleteGcpCmd())
	cmd.AddCommand(newCollectionAgentsDeleteGenericCmd())
	cmd.AddCommand(newCollectionAgentsDeleteGenericOauthClientCmd())
	cmd.AddCommand(newCollectionAgentsDeleteGenericTokenCmd())
	return cmd
}

func newCollectionAgentsDeleteAwsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws <collection_agent_id>",
		Short: "Delete an AWS collection agent",
		Long:  "Deregister an AWS collection agent.\n\nIts deployment is left without an agent. Reprovision that deployment before registering\nanother agent on it.\n\nAn agent cannot be deleted while its deployment still has a connection running through\nit. Delete or move those connections first.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.DeleteAwsCollectionAgent(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionAgentsDeleteAzureCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure <collection_agent_id>",
		Short: "Delete an Azure collection agent",
		Long:  "Deregister an Azure collection agent.\n\nIts deployment is left without an agent. Reprovision that deployment before registering\nanother agent on it.\n\nAn agent cannot be deleted while its deployment still has a connection running through it.\nDelete or move those connections first.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.DeleteAzureCollectionAgent(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionAgentsDeleteGcpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp <collection_agent_id>",
		Short: "Delete a GCP collection agent",
		Long:  "Deregister a GCP collection agent.\n\nIts deployment is left without an agent. Reprovision that deployment before registering\nanother agent on it.\n\nAn agent cannot be deleted while its deployment still has a connection running through it.\nDelete or move those connections first.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.DeleteGcpCollectionAgent(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionAgentsDeleteGenericCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic <collection_agent_id>",
		Short: "Delete a generic collection agent",
		Long:  "Deregister a generic collection agent.\n\nEvery credential created for its deployment is deleted with it, so a running agent stops\nbeing able to connect. Its deployment is left without an agent. Reprovision that deployment\nbefore registering another agent on it.\n\nAn agent cannot be deleted while its deployment still has a connection running through it.\nDelete or move those connections first.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.DeleteGenericCollectionAgent(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionAgentsDeleteGenericOauthClientCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic-oauth-client <credential_id>",
		Short: "Delete a generic collection agent OAuth client",
		Long:  "Delete an OAuth client.\n\nAn agent still running with it stops being able to get new access tokens. Access tokens it\nalready holds stay valid until they expire.\n\nDeleting an id your account does not hold, or has already deleted, also returns 204.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.DeleteGenericCollectionAgentOauthClient(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionAgentsDeleteGenericTokenCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic-token <credential_id>",
		Short: "Delete a generic collection agent token",
		Long:  "Delete a token. An agent still running with it stops being able to connect.\n\nDeleting an id your account does not hold, or has already deleted, also returns 204.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.DeleteGenericCollectionAgentToken(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionAgentsGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get collection agent",
	}
	cmd.AddCommand(newCollectionAgentsGetAwsCmd())
	cmd.AddCommand(newCollectionAgentsGetAzureCmd())
	cmd.AddCommand(newCollectionAgentsGetGcpCmd())
	cmd.AddCommand(newCollectionAgentsGetGenericCmd())
	cmd.AddCommand(newCollectionAgentsGetGenericOauthClientCmd())
	cmd.AddCommand(newCollectionAgentsGetGenericTokenCmd())
	return cmd
}

func newCollectionAgentsGetAwsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws <collection_agent_id>",
		Short: "Get an AWS collection agent",
		Long:  "Get one collection agent running on AWS, including its external id.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.GetAwsCollectionAgent(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "external_id", "id", "image_build", "image_version", "is_remote_upgradeable", "lambda_function_arn", "last_updated_time", "name")
		},
	}
	return cmd
}

func newCollectionAgentsGetAzureCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure <collection_agent_id>",
		Short: "Get an Azure collection agent",
		Long:  "Get one collection agent running on Azure.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.GetAzureCollectionAgent(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "function_app_url", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	return cmd
}

func newCollectionAgentsGetGcpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp <collection_agent_id>",
		Short: "Get a GCP collection agent",
		Long:  "Get one collection agent running on GCP.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.GetGcpCollectionAgent(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "cloud_run_url", "created_time", "deployment_id", "enabled", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	return cmd
}

func newCollectionAgentsGetGenericCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic <collection_agent_id>",
		Short: "Get a generic collection agent",
		Long:  "Get one generic collection agent.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.GetGenericCollectionAgent(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	return cmd
}

func newCollectionAgentsGetGenericOauthClientCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic-oauth-client <credential_id>",
		Short: "Get a generic collection agent OAuth client",
		Long:  "Get one OAuth client. The secret is not part of it.\n\nAn id that names another kind of credential, or no credential in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.GetGenericCollectionAgentOauthClient(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "client_id", "created_time", "deployment_id", "description", "expiration_time", "id", "scopes", "type")
		},
	}
	return cmd
}

func newCollectionAgentsGetGenericTokenCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic-token <credential_id>",
		Short: "Get a generic collection agent token",
		Long:  "Get one token. The secret is not part of it.\n\nAn id that names another kind of credential, or no credential in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.GetGenericCollectionAgentToken(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "created_time", "deployment_id", "description", "id", "mcd_id", "type")
		},
	}
	return cmd
}

func newCollectionAgentsListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List collection agents",
		Long:  "List the collection agents in your account, on every platform.\n\nOnly agents on deployments running Monte Carlo's current collection platform are listed.\nAgents on the older platform are managed separately and do not appear here.\n\nAgents are sorted by name, ignoring case. Agents with no name come last.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.ListCollectionAgents(ctx)
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderList(cmd, out, []string{"id", "name", "platform", "enabled", "deployment_id"})
		},
	}
	cmd.AddCommand(newCollectionAgentsListGenericCredentialsCmd())
	return cmd
}

func newCollectionAgentsListGenericCredentialsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic-credentials",
		Short: "List generic collection agent credentials",
		Long:  "List the credentials your generic collection agents present, of both kinds.\n\nNo secret is part of the list. Credentials are sorted oldest first.\n\nThe list is not paged. A deployment holds a credential or two in normal use, so the list\nstays short, but nothing caps how many you can create.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.ListGenericCollectionAgentCredentials(ctx)
			if changed(cmd, "deployment-id") {
				deploymentId, err := flagString(cmd, "deployment-id")
				if err != nil {
					return err
				}
				req = req.DeploymentId(deploymentId)
			}
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderList(cmd, out, []string{"id", "type", "deployment_id", "description", "created_time"})
		},
	}
	cmd.Flags().String("deployment-id", "", "Only the credentials of this deployment's agent.")
	return cmd
}

func newCollectionAgentsRegisterCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "register",
		Short: "Register collection agent",
	}
	cmd.AddCommand(newCollectionAgentsRegisterAwsCmd())
	cmd.AddCommand(newCollectionAgentsRegisterAzureCmd())
	cmd.AddCommand(newCollectionAgentsRegisterGcpCmd())
	cmd.AddCommand(newCollectionAgentsRegisterGenericCmd())
	return cmd
}

func newCollectionAgentsRegisterAwsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws",
		Short: "Register an AWS collection agent",
		Long:  "Register the collection agent a deployment was provisioned for, on AWS.\n\nThis is the second of the two calls that connect an agent. Provision the deployment\nfirst, deploy the agent yourself, then call this with the deployment's id, the agent's\nLambda function ARN, and the ARN of the role Monte Carlo assumes to invoke it. The\ndeployment must have been provisioned for an AWS collection agent, and that role's trust\npolicy must already carry the deployment's external id.\n\nMonte Carlo reaches the agent and checks it before enabling it. If the check fails,\nnothing is registered, and you can call this again once the cause is fixed.\n\nCalling this a second time with the same ARNs returns the agent that is already there, so\na retry is safe. Registering different ARNs over an agent that is already registered is\nrefused. A new `name` is applied either way.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.RegisterAwsCollectionAgent(ctx)
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			lambdaFunctionArn, err := flagString(cmd, "lambda-function-arn")
			if err != nil {
				return err
			}
			roleArn, err := flagString(cmd, "role-arn")
			if err != nil {
				return err
			}
			body := sdk.NewAwsCollectionAgentIn(deploymentId, lambdaFunctionArn, roleArn)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.AwsCollectionAgentIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "external_id", "id", "image_build", "image_version", "is_remote_upgradeable", "lambda_function_arn", "last_updated_time", "name")
		},
	}
	cmd.Flags().String("deployment-id", "", "Deployment to register the collection agent on. It must already hold an unregistered AWS collection agent.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("lambda-function-arn", "", "ARN of the Lambda function Monte Carlo should invoke.")
	_ = cmd.MarkFlagRequired("lambda-function-arn")
	cmd.Flags().String("role-arn", "", "ARN of the role Monte Carlo assumes to invoke the function. Its trust policy must already carry the deployment's external id.")
	_ = cmd.MarkFlagRequired("role-arn")
	cmd.Flags().String("name", "", "Display name for the collection agent. Replaces the name it currently has.")
	return cmd
}

func newCollectionAgentsRegisterAzureCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure",
		Short: "Register an Azure collection agent",
		Long:  "Register the collection agent a deployment was provisioned for, on Azure.\n\nThis is the second of the two calls that connect an agent. Provision the deployment first,\ndeploy the agent yourself, then call this with the deployment's id, the function app's URL,\nand the credentials for the way you want Monte Carlo to authenticate. The deployment must\nhave been provisioned for an Azure collection agent.\n\nMonte Carlo reaches the agent and checks it before enabling it. If the check fails, nothing\nis registered, and you can call this again once the cause is fixed.\n\nCalling this a second time with the same details returns the agent that is already there,\nso a retry is safe. Registering a different function app or different credentials over an\nagent that is already registered is refused. A new `name` is applied either way.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.RegisterAzureCollectionAgent(ctx)
			authenticationTypeValue, err := flagString(cmd, "authentication-type")
			if err != nil {
				return err
			}
			authenticationType, err := sdk.NewAzureAgentAuthenticationTypeFromValue(authenticationTypeValue)
			if err != nil {
				return err
			}
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			functionAppUrl, err := flagString(cmd, "function-app-url")
			if err != nil {
				return err
			}
			body := sdk.NewAzureCollectionAgentIn(*authenticationType, deploymentId, functionAppUrl)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "function-app-key-app-key", "function-app-key-app-key-prompt") {
				if err := requireAny(cmd, "function-app-key-app-key", "function-app-key-app-key-prompt"); err != nil {
					return err
				}
				functionAppKeyAppKey, err := flagSecret(cmd, "function-app-key-app-key")
				if err != nil {
					return err
				}
				nested := sdk.NewFunctionAppKeyCredentialsIn(functionAppKeyAppKey)
				body.SetFunctionAppKey(*nested)
			}
			if changed(cmd, "service-principal-audience", "service-principal-client-id", "service-principal-client-secret", "service-principal-client-secret-prompt", "service-principal-tenant-id") {
				if err := requireAny(cmd, "service-principal-audience"); err != nil {
					return err
				}
				servicePrincipalAudience, err := flagString(cmd, "service-principal-audience")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-client-id"); err != nil {
					return err
				}
				servicePrincipalClientId, err := flagString(cmd, "service-principal-client-id")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-client-secret", "service-principal-client-secret-prompt"); err != nil {
					return err
				}
				servicePrincipalClientSecret, err := flagSecret(cmd, "service-principal-client-secret")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-tenant-id"); err != nil {
					return err
				}
				servicePrincipalTenantId, err := flagString(cmd, "service-principal-tenant-id")
				if err != nil {
					return err
				}
				nested := sdk.NewServicePrincipalCredentialsIn(servicePrincipalAudience, servicePrincipalClientId, servicePrincipalClientSecret, servicePrincipalTenantId)
				body.SetServicePrincipal(*nested)
			}
			req = req.AzureCollectionAgentIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "function_app_url", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	cmd.Flags().String("authentication-type", "", "How Monte Carlo authenticates when it calls the agent. Send it together with the matching credentials object.")
	_ = cmd.RegisterFlagCompletionFunc("authentication-type", enumCompletion(sdk.AllowedAzureAgentAuthenticationTypeEnumValues))
	_ = cmd.MarkFlagRequired("authentication-type")
	cmd.Flags().String("deployment-id", "", "Deployment to register the collection agent on. It must already hold an unregistered Azure collection agent.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("function-app-url", "", "URL of the function app Monte Carlo should call.")
	_ = cmd.MarkFlagRequired("function-app-url")
	cmd.Flags().String("name", "", "Display name for the collection agent. Replaces the name it currently has.")
	cmd.Flags().String("function-app-key-app-key", "", "Function app key Monte Carlo presents when it calls the agent.")
	cmd.Flags().Bool("function-app-key-app-key-prompt", false, "Read --function-app-key-app-key from a hidden prompt instead of the command line.")
	cmd.Flags().String("service-principal-audience", "", "Audience the issued token is for, usually the function app's application id.")
	cmd.Flags().String("service-principal-client-id", "", "Application (client) id of the service principal.")
	cmd.Flags().String("service-principal-client-secret", "", "Client secret of the service principal.")
	cmd.Flags().Bool("service-principal-client-secret-prompt", false, "Read --service-principal-client-secret from a hidden prompt instead of the command line.")
	cmd.Flags().String("service-principal-tenant-id", "", "Directory (tenant) id the service principal lives in.")
	return cmd
}

func newCollectionAgentsRegisterGcpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp",
		Short: "Register a GCP collection agent",
		Long:  "Register the collection agent a deployment was provisioned for, on GCP.\n\nThis is the second of the two calls that connect an agent. Provision the deployment first,\ndeploy the agent yourself, then call this with the deployment's id, the Cloud Run service's\nURL, and the credentials Monte Carlo should authenticate with. The deployment must have\nbeen provisioned for a GCP collection agent.\n\nMonte Carlo reaches the agent and checks it before enabling it. If the check fails, nothing\nis registered, and you can call this again once the cause is fixed.\n\nCalling this a second time with the same details returns the agent that is already there,\nso a retry is safe. Registering a different Cloud Run service or different credentials over\nan agent that is already registered is refused. A new `name` is applied either way.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.RegisterGcpCollectionAgent(ctx)
			authenticationTypeValue, err := flagString(cmd, "authentication-type")
			if err != nil {
				return err
			}
			authenticationType, err := sdk.NewGcpAgentAuthenticationTypeFromValue(authenticationTypeValue)
			if err != nil {
				return err
			}
			cloudRunUrl, err := flagString(cmd, "cloud-run-url")
			if err != nil {
				return err
			}
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			body := sdk.NewGcpCollectionAgentIn(*authenticationType, cloudRunUrl, deploymentId)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "service-account-key", "service-account-key-prompt") {
				serviceAccountKey, err := flagSecret(cmd, "service-account-key")
				if err != nil {
					return err
				}
				body.SetServiceAccountKey(serviceAccountKey)
			}
			if changed(cmd, "auth-headers-headers") {
				if err := requireAny(cmd, "auth-headers-headers"); err != nil {
					return err
				}
				authHeadersHeaders, err := flagStringMap(cmd, "auth-headers-headers")
				if err != nil {
					return err
				}
				nested := sdk.NewAuthHeadersCredentialsIn(authHeadersHeaders)
				body.SetAuthHeaders(*nested)
			}
			req = req.GcpCollectionAgentIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "cloud_run_url", "created_time", "deployment_id", "enabled", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	cmd.Flags().String("authentication-type", "", "How Monte Carlo authenticates when it calls the agent. Send it together with the matching credentials.")
	_ = cmd.RegisterFlagCompletionFunc("authentication-type", enumCompletion(sdk.AllowedGcpAgentAuthenticationTypeEnumValues))
	_ = cmd.MarkFlagRequired("authentication-type")
	cmd.Flags().String("cloud-run-url", "", "URL of the Cloud Run service Monte Carlo should call.")
	_ = cmd.MarkFlagRequired("cloud-run-url")
	cmd.Flags().String("deployment-id", "", "Deployment to register the collection agent on. It must already hold an unregistered GCP collection agent.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("name", "", "Display name for the collection agent. Replaces the name it currently has.")
	cmd.Flags().String("service-account-key", "", "Credentials for GCP_JSON_SERVICE_ACCOUNT_KEY, as the contents of the JSON key file Google issued for the service account. Send this or auth_headers, never both. It replaces the stored credentials rather than merging into them.")
	cmd.Flags().Bool("service-account-key-prompt", false, "Read --service-account-key from a hidden prompt instead of the command line.")
	cmd.Flags().StringArray("auth-headers-headers", nil, "Header names, each mapped to the value to send for it. Names have to be valid HTTP header names. At most 20 headers, each value up to 8192 characters. Repeat key=value, or pass @file holding JSON.")
	return cmd
}

func newCollectionAgentsRegisterGenericCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic",
		Short: "Register a generic collection agent",
		Long:  "Enable the generic collection agent a deployment was provisioned for.\n\nA generic agent connects out to Monte Carlo, so registering it takes three steps.\nProvision the deployment, create a credential for it, and run the agent with that\ncredential. Then call this with the deployment's id. Monte Carlo checks that the agent has\nconnected and enables it.\n\nIf the agent has not connected yet, this answers 503 and nothing changes, so call it again\nonce the agent is up. Calling it on an agent that is already enabled returns the agent, so\na retry is safe. A new `name` is applied either way.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.RegisterGenericCollectionAgent(ctx)
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			body := sdk.NewGenericCollectionAgentIn(deploymentId)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.GenericCollectionAgentIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	cmd.Flags().String("deployment-id", "", "Deployment whose generic collection agent to enable. It must have been provisioned for one, and the agent must be running with a credential created for this deployment.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("name", "", "Display name for the collection agent. Replaces the name it currently has.")
	return cmd
}

func newCollectionAgentsUpdateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update collection agent",
	}
	cmd.AddCommand(newCollectionAgentsUpdateAwsCmd())
	cmd.AddCommand(newCollectionAgentsUpdateAzureCmd())
	cmd.AddCommand(newCollectionAgentsUpdateGcpCmd())
	cmd.AddCommand(newCollectionAgentsUpdateGenericCmd())
	return cmd
}

func newCollectionAgentsUpdateAwsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws <collection_agent_id>",
		Short: "Update an AWS collection agent",
		Long:  "Change the Lambda function, the role or the name of an AWS collection agent.\n\nSend any of the fields, in any combination. Anything you leave out is kept as it is. An\nagent that has no Lambda function yet needs one supplied here, since there would otherwise\nbe nothing for Monte Carlo to reach.\n\nMonte Carlo reaches the agent and checks it again before saving the change, and re-enables\nthe agent if it was disabled. A successful response therefore always describes a working\nagent. If the check fails, nothing about the agent changes. Sending only `name` skips the\ncheck.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.UpdateAwsCollectionAgent(ctx, args[0])
			body := sdk.NewAwsCollectionAgentPatch()
			if changed(cmd, "lambda-function-arn") {
				lambdaFunctionArn, err := flagString(cmd, "lambda-function-arn")
				if err != nil {
					return err
				}
				body.SetLambdaFunctionArn(lambdaFunctionArn)
			}
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "role-arn") {
				roleArn, err := flagString(cmd, "role-arn")
				if err != nil {
					return err
				}
				body.SetRoleArn(roleArn)
			}
			req = req.AwsCollectionAgentPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "external_id", "id", "image_build", "image_version", "is_remote_upgradeable", "lambda_function_arn", "last_updated_time", "name")
		},
	}
	cmd.Flags().String("lambda-function-arn", "", "ARN of the Lambda function Monte Carlo should invoke.")
	cmd.Flags().String("name", "", "Display name for the collection agent. Replaces the name it currently has.")
	cmd.Flags().String("role-arn", "", "ARN of the role Monte Carlo assumes to invoke the function. Its trust policy must already carry the deployment's external id.")
	return cmd
}

func newCollectionAgentsUpdateAzureCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure <collection_agent_id>",
		Short: "Update an Azure collection agent",
		Long:  "Change the function app, the credentials, the authentication type or the name.\n\nSend any of the fields, in any combination. An agent that has no function app URL yet needs\none supplied here, since there would otherwise be nothing for Monte Carlo to reach. Sending\ncredentials replaces the stored ones, so send every field of the object you send, along with\nthe matching `authentication_type`. Sending both is also how you move an agent from one\nauthentication type to the other. An agent that authenticates some other way refuses a\ncredentials or authentication type change, since this endpoint only manages the two Azure\nfunction authentication types.\n\nMonte Carlo reaches the agent and checks it again before saving the change, and re-enables\nthe agent if it was disabled. A successful response therefore always describes a working\nagent. If the check fails, nothing about the agent changes. Sending only `name` skips the\ncheck.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.UpdateAzureCollectionAgent(ctx, args[0])
			body := sdk.NewAzureCollectionAgentPatch()
			if changed(cmd, "authentication-type") {
				authenticationTypeValue, err := flagString(cmd, "authentication-type")
				if err != nil {
					return err
				}
				authenticationType, err := sdk.NewAzureAgentAuthenticationTypeFromValue(authenticationTypeValue)
				if err != nil {
					return err
				}
				body.SetAuthenticationType(*authenticationType)
			}
			if changed(cmd, "function-app-url") {
				functionAppUrl, err := flagString(cmd, "function-app-url")
				if err != nil {
					return err
				}
				body.SetFunctionAppUrl(functionAppUrl)
			}
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "function-app-key-app-key", "function-app-key-app-key-prompt") {
				if err := requireAny(cmd, "function-app-key-app-key", "function-app-key-app-key-prompt"); err != nil {
					return err
				}
				functionAppKeyAppKey, err := flagSecret(cmd, "function-app-key-app-key")
				if err != nil {
					return err
				}
				nested := sdk.NewFunctionAppKeyCredentialsIn(functionAppKeyAppKey)
				body.SetFunctionAppKey(*nested)
			}
			if changed(cmd, "service-principal-audience", "service-principal-client-id", "service-principal-client-secret", "service-principal-client-secret-prompt", "service-principal-tenant-id") {
				if err := requireAny(cmd, "service-principal-audience"); err != nil {
					return err
				}
				servicePrincipalAudience, err := flagString(cmd, "service-principal-audience")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-client-id"); err != nil {
					return err
				}
				servicePrincipalClientId, err := flagString(cmd, "service-principal-client-id")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-client-secret", "service-principal-client-secret-prompt"); err != nil {
					return err
				}
				servicePrincipalClientSecret, err := flagSecret(cmd, "service-principal-client-secret")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-tenant-id"); err != nil {
					return err
				}
				servicePrincipalTenantId, err := flagString(cmd, "service-principal-tenant-id")
				if err != nil {
					return err
				}
				nested := sdk.NewServicePrincipalCredentialsIn(servicePrincipalAudience, servicePrincipalClientId, servicePrincipalClientSecret, servicePrincipalTenantId)
				body.SetServicePrincipal(*nested)
			}
			req = req.AzureCollectionAgentPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "function_app_url", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	cmd.Flags().String("authentication-type", "", "How Monte Carlo authenticates when it calls the agent. Send it together with the matching credentials object.")
	_ = cmd.RegisterFlagCompletionFunc("authentication-type", enumCompletion(sdk.AllowedAzureAgentAuthenticationTypeEnumValues))
	cmd.Flags().String("function-app-url", "", "URL of the function app Monte Carlo should call.")
	cmd.Flags().String("name", "", "Display name for the collection agent. Replaces the name it currently has.")
	cmd.Flags().String("function-app-key-app-key", "", "Function app key Monte Carlo presents when it calls the agent.")
	cmd.Flags().Bool("function-app-key-app-key-prompt", false, "Read --function-app-key-app-key from a hidden prompt instead of the command line.")
	cmd.Flags().String("service-principal-audience", "", "Audience the issued token is for, usually the function app's application id.")
	cmd.Flags().String("service-principal-client-id", "", "Application (client) id of the service principal.")
	cmd.Flags().String("service-principal-client-secret", "", "Client secret of the service principal.")
	cmd.Flags().Bool("service-principal-client-secret-prompt", false, "Read --service-principal-client-secret from a hidden prompt instead of the command line.")
	cmd.Flags().String("service-principal-tenant-id", "", "Directory (tenant) id the service principal lives in.")
	return cmd
}

func newCollectionAgentsUpdateGcpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp <collection_agent_id>",
		Short: "Update a GCP collection agent",
		Long:  "Change the Cloud Run service, the credentials, the authentication type or the name.\n\nSend any of the fields, in any combination. An agent that has no Cloud Run URL yet needs\none supplied here, since there would otherwise be nothing for Monte Carlo to reach. Sending\ncredentials replaces the stored ones, and sending `authentication_type` along with them\nmoves the agent between the two GCP authentication types. An agent that authenticates some\nother way refuses a Cloud Run URL or credentials change, since this endpoint only manages\nthe two GCP authentication types.\n\nMonte Carlo reaches the agent and checks it again before saving the change, and re-enables\nthe agent if it was disabled. A successful response therefore always describes a working\nagent. If the check fails, nothing about the agent changes. Sending only `name` skips the\ncheck.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.UpdateGcpCollectionAgent(ctx, args[0])
			body := sdk.NewGcpCollectionAgentPatch()
			if changed(cmd, "authentication-type") {
				authenticationTypeValue, err := flagString(cmd, "authentication-type")
				if err != nil {
					return err
				}
				authenticationType, err := sdk.NewGcpAgentAuthenticationTypeFromValue(authenticationTypeValue)
				if err != nil {
					return err
				}
				body.SetAuthenticationType(*authenticationType)
			}
			if changed(cmd, "cloud-run-url") {
				cloudRunUrl, err := flagString(cmd, "cloud-run-url")
				if err != nil {
					return err
				}
				body.SetCloudRunUrl(cloudRunUrl)
			}
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "service-account-key", "service-account-key-prompt") {
				serviceAccountKey, err := flagSecret(cmd, "service-account-key")
				if err != nil {
					return err
				}
				body.SetServiceAccountKey(serviceAccountKey)
			}
			if changed(cmd, "auth-headers-headers") {
				if err := requireAny(cmd, "auth-headers-headers"); err != nil {
					return err
				}
				authHeadersHeaders, err := flagStringMap(cmd, "auth-headers-headers")
				if err != nil {
					return err
				}
				nested := sdk.NewAuthHeadersCredentialsIn(authHeadersHeaders)
				body.SetAuthHeaders(*nested)
			}
			req = req.GcpCollectionAgentPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "cloud_run_url", "created_time", "deployment_id", "enabled", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	cmd.Flags().String("authentication-type", "", "How Monte Carlo authenticates when it calls the agent. Send it together with the matching credentials.")
	_ = cmd.RegisterFlagCompletionFunc("authentication-type", enumCompletion(sdk.AllowedGcpAgentAuthenticationTypeEnumValues))
	cmd.Flags().String("cloud-run-url", "", "URL of the Cloud Run service Monte Carlo should call.")
	cmd.Flags().String("name", "", "Display name for the collection agent. Replaces the name it currently has.")
	cmd.Flags().String("service-account-key", "", "Credentials for GCP_JSON_SERVICE_ACCOUNT_KEY, as the contents of the JSON key file Google issued for the service account. Send this or auth_headers, never both. It replaces the stored credentials rather than merging into them.")
	cmd.Flags().Bool("service-account-key-prompt", false, "Read --service-account-key from a hidden prompt instead of the command line.")
	cmd.Flags().StringArray("auth-headers-headers", nil, "Header names, each mapped to the value to send for it. Names have to be valid HTTP header names. At most 20 headers, each value up to 8192 characters. Repeat key=value, or pass @file holding JSON.")
	return cmd
}

func newCollectionAgentsUpdateGenericCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generic <collection_agent_id>",
		Short: "Update a generic collection agent",
		Long:  "Rename a generic collection agent.\n\nThe name is the only thing you can change. How the agent authenticates is managed through\nits deployment's credentials, and where it runs is yours to manage. Sending an empty body\nleaves the agent as it is and returns it.\n\nAn id that names an agent on another platform, or no agent in your account, returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionAgentsAPI.UpdateGenericCollectionAgent(ctx, args[0])
			body := sdk.NewGenericCollectionAgentPatch()
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.GenericCollectionAgentPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "authentication_type", "created_time", "deployment_id", "enabled", "id", "image_build", "image_version", "is_remote_upgradeable", "last_updated_time", "name")
		},
	}
	cmd.Flags().String("name", "", "Display name for the collection agent. Replaces the name it currently has.")
	return cmd
}
