// Code generated by api-codegen; DO NOT EDIT.

package cmd

import (
	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newCollectionDataStoresCmd())
}

func newCollectionDataStoresCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "collection-data-stores",
		Short: "Collection data stores",
	}
	cmd.AddCommand(newCollectionDataStoresDeleteCmd())
	cmd.AddCommand(newCollectionDataStoresGetCmd())
	cmd.AddCommand(newCollectionDataStoresListCmd())
	cmd.AddCommand(newCollectionDataStoresRegisterCmd())
	cmd.AddCommand(newCollectionDataStoresUpdateCmd())
	return cmd
}

func newCollectionDataStoresDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete collection data store",
	}
	cmd.AddCommand(newCollectionDataStoresDeleteAwsCmd())
	cmd.AddCommand(newCollectionDataStoresDeleteAzureCmd())
	cmd.AddCommand(newCollectionDataStoresDeleteGcpCmd())
	return cmd
}

func newCollectionDataStoresDeleteAwsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws <collection_data_store_id>",
		Short: "Delete an AWS collection data store",
		Long:  "Deregister an S3 data store.\n\nIts deployment is left without one. Reprovision that deployment before registering another.\n\nThe bucket itself is yours and is not deleted.\n\nA data store cannot be deleted while its deployment still has a connection running through\nit. Delete or move those connections first.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete aws collection data store"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.DeleteAwsCollectionDataStore(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionDataStoresDeleteAzureCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure <collection_data_store_id>",
		Short: "Delete an Azure collection data store",
		Long:  "Deregister a data store held in Azure Blob Storage.\n\nIts deployment is left without one. Reprovision that deployment before registering another.\n\nThe container itself is yours and is not deleted.\n\nA data store cannot be deleted while its deployment still has a connection running through\nit. Delete or move those connections first.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete azure collection data store"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.DeleteAzureCollectionDataStore(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionDataStoresDeleteGcpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp <collection_data_store_id>",
		Short: "Delete a GCP collection data store",
		Long:  "Deregister a data store held in Google Cloud Storage.\n\nIts deployment is left without one. Reprovision that deployment before registering another.\n\nThe bucket itself is yours and is not deleted.\n\nA data store cannot be deleted while its deployment still has a connection running through\nit. Delete or move those connections first.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete gcp collection data store"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.DeleteGcpCollectionDataStore(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCollectionDataStoresGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get collection data store",
	}
	cmd.AddCommand(newCollectionDataStoresGetAwsCmd())
	cmd.AddCommand(newCollectionDataStoresGetAzureCmd())
	cmd.AddCommand(newCollectionDataStoresGetGcpCmd())
	return cmd
}

func newCollectionDataStoresGetAwsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws <collection_data_store_id>",
		Short: "Get an AWS collection data store",
		Long:  "Get one data store held in an S3 bucket, including its external id.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.GetAwsCollectionDataStore(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "bucket_name", "external_id")
		},
	}
	return cmd
}

func newCollectionDataStoresGetAzureCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure <collection_data_store_id>",
		Short: "Get an Azure collection data store",
		Long:  "Read one data store held in Azure Blob Storage.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.GetAzureCollectionDataStore(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "container_name")
		},
	}
	return cmd
}

func newCollectionDataStoresGetGcpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp <collection_data_store_id>",
		Short: "Get a GCP collection data store",
		Long:  "Read one data store held in Google Cloud Storage.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.GetGcpCollectionDataStore(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "bucket_name")
		},
	}
	return cmd
}

func newCollectionDataStoresListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List collection data stores",
		Long:  "List the data stores in your account, on every platform.\n\nOnly data stores on deployments running Monte Carlo's current collection platform are\nlisted. Data stores on the older platform are managed separately and do not appear here.\n\nData stores are sorted by name, ignoring case. Data stores with no name come last.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.ListCollectionDataStores(ctx)
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderList(cmd, out, []string{"id", "name", "platform", "storage_type", "enabled", "deployment_id"})
		},
	}
	return cmd
}

func newCollectionDataStoresRegisterCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "register",
		Short: "Register collection data store",
	}
	cmd.AddCommand(newCollectionDataStoresRegisterAwsCmd())
	cmd.AddCommand(newCollectionDataStoresRegisterAzureCmd())
	cmd.AddCommand(newCollectionDataStoresRegisterGcpCmd())
	return cmd
}

func newCollectionDataStoresRegisterAwsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws",
		Short: "Register an AWS collection data store",
		Long:  "Register the data store a deployment was provisioned for, on AWS.\n\nThe second of the two calls that connect a data store. Provision the deployment first, then\ncreate the bucket and the role yourself. The role's trust policy must already carry the\ndeployment's external id.\n\nMonte Carlo writes a test object to the bucket and reads it back before enabling the data\nstore. Nothing is registered if that fails, so call this again once you have fixed the\ncause.\n\nSending the same bucket and role twice returns the data store already there, so a retry is\nsafe. A different bucket or role over a registered one is refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.RegisterAwsCollectionDataStore(ctx)
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			bucketName, err := flagString(cmd, "bucket-name")
			if err != nil {
				return err
			}
			roleArn, err := flagString(cmd, "role-arn")
			if err != nil {
				return err
			}
			body := sdk.NewAwsCollectionDataStoreIn(deploymentId, bucketName, roleArn)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.AwsCollectionDataStoreIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "bucket_name", "external_id")
		},
	}
	cmd.Flags().String("deployment-id", "", "Deployment to register the data store on. It must already hold an unregistered S3 data store.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("bucket-name", "", "Name of the S3 bucket Monte Carlo should use.")
	_ = cmd.MarkFlagRequired("bucket-name")
	cmd.Flags().String("role-arn", "", "ARN of the role Monte Carlo assumes to access the bucket. Its trust policy must already carry the deployment's external id.")
	_ = cmd.MarkFlagRequired("role-arn")
	cmd.Flags().String("name", "", "Display name for the data store. Replaces the name its deployment gave it.")
	return cmd
}

func newCollectionDataStoresRegisterAzureCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure",
		Short: "Register an Azure collection data store",
		Long:  "Register the data store a deployment was provisioned for, in Azure Blob Storage.\n\nThe second of the two calls that connect a data store. Provision the deployment first, then\ncreate the container yourself and grant Monte Carlo access to it.\n\nSend `authentication_type` with the one credentials object that goes with it. The\ncredentials name the storage account, so it is not a field of its own. A connection string\ncarries it, and a service principal names it in `account_url`.\n\nMonte Carlo writes a test object to the container and reads it back before enabling the data\nstore. Nothing is registered if that fails, so call this again once you have fixed the\ncause.\n\nSending the same details twice returns the data store already there, so a retry is safe.\nDifferent details over a registered one are refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.RegisterAzureCollectionDataStore(ctx)
			authenticationTypeValue, err := flagString(cmd, "authentication-type")
			if err != nil {
				return err
			}
			authenticationType, err := sdk.NewAzureDataStoreAuthenticationTypeFromValue(authenticationTypeValue)
			if err != nil {
				return err
			}
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			containerName, err := flagString(cmd, "container-name")
			if err != nil {
				return err
			}
			body := sdk.NewAzureCollectionDataStoreIn(*authenticationType, deploymentId, containerName)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "service-principal-tenant-id", "service-principal-client-id", "service-principal-client-secret", "service-principal-client-secret-prompt", "service-principal-account-url", "service-principal-account-name") {
				if err := requireAny(cmd, "service-principal-tenant-id"); err != nil {
					return err
				}
				servicePrincipalTenantId, err := flagString(cmd, "service-principal-tenant-id")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-client-id"); err != nil {
					return err
				}
				servicePrincipalClientId, err := flagString(cmd, "service-principal-client-id")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-client-secret", "service-principal-client-secret-prompt"); err != nil {
					return err
				}
				servicePrincipalClientSecret, err := flagSecret(cmd, "service-principal-client-secret")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-account-url"); err != nil {
					return err
				}
				servicePrincipalAccountUrl, err := flagString(cmd, "service-principal-account-url")
				if err != nil {
					return err
				}
				nested := sdk.NewStorageServicePrincipalCredentialsIn(servicePrincipalTenantId, servicePrincipalClientId, servicePrincipalClientSecret, servicePrincipalAccountUrl)
				if changed(cmd, "service-principal-account-name") {
					servicePrincipalAccountName, err := flagString(cmd, "service-principal-account-name")
					if err != nil {
						return err
					}
					nested.SetAccountName(servicePrincipalAccountName)
				}
				body.SetServicePrincipal(*nested)
			}
			if changed(cmd, "storage-account-keys-connection-string", "storage-account-keys-connection-string-prompt") {
				if err := requireAny(cmd, "storage-account-keys-connection-string", "storage-account-keys-connection-string-prompt"); err != nil {
					return err
				}
				storageAccountKeysConnectionString, err := flagSecret(cmd, "storage-account-keys-connection-string")
				if err != nil {
					return err
				}
				nested := sdk.NewStorageAccountKeysCredentialsIn(storageAccountKeysConnectionString)
				body.SetStorageAccountKeys(*nested)
			}
			req = req.AzureCollectionDataStoreIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "container_name")
		},
	}
	cmd.Flags().String("authentication-type", "", "How Monte Carlo authenticates to the storage account. Send it together with the matching credentials object.")
	_ = cmd.RegisterFlagCompletionFunc("authentication-type", enumCompletion(sdk.AllowedAzureDataStoreAuthenticationTypeEnumValues))
	_ = cmd.MarkFlagRequired("authentication-type")
	cmd.Flags().String("deployment-id", "", "Deployment to register the data store on. It must already hold an unregistered Azure data store.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("container-name", "", "Name of the blob container Monte Carlo should use.")
	_ = cmd.MarkFlagRequired("container-name")
	cmd.Flags().String("name", "", "Display name for the data store. Replaces the name its deployment gave it.")
	cmd.Flags().String("service-principal-tenant-id", "", "Directory (tenant) id the service principal lives in.")
	cmd.Flags().String("service-principal-client-id", "", "Application (client) id of the service principal.")
	cmd.Flags().String("service-principal-client-secret", "", "Client secret of the service principal. Visible in the process list; --service-principal-client-secret-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("service-principal-client-secret-prompt", false, "Read --service-principal-client-secret from a hidden prompt instead of the command line.")
	cmd.Flags().String("service-principal-account-url", "", "URL of the storage account Monte Carlo sends requests to. A private endpoint or a custom host works, so this is not required to be under blob.core.windows.net.")
	cmd.Flags().String("service-principal-account-name", "", "Name of the storage account, needed only when account_url does not start with it. Monte Carlo takes the first label of the host otherwise, which is right for a standard or private-link URL but not for a custom ingress host.")
	cmd.Flags().String("storage-account-keys-connection-string", "", "Connection string for the storage account holding the container. It carries the account key, so treat it as a secret. Visible in the process list; --storage-account-keys-connection-string-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("storage-account-keys-connection-string-prompt", false, "Read --storage-account-keys-connection-string from a hidden prompt instead of the command line.")
	return cmd
}

func newCollectionDataStoresRegisterGcpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp",
		Short: "Register a GCP collection data store",
		Long:  "Register the data store a deployment was provisioned for, in Google Cloud Storage.\n\nThe second of the two calls that connect a data store. Provision the deployment first, then\ncreate the bucket yourself and grant the service account access to it.\n\nSend the service account key as the contents of the JSON key file Google issued for it.\n\nMonte Carlo writes a test object to the bucket and reads it back before enabling the data\nstore. Nothing is registered if that fails, so call this again once you have fixed the\ncause.\n\nSending the same details twice returns the data store already there, so a retry is safe.\nDifferent details over a registered one are refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := requireAny(cmd, "service-account-key", "service-account-key-prompt"); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.RegisterGcpCollectionDataStore(ctx)
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			bucketName, err := flagString(cmd, "bucket-name")
			if err != nil {
				return err
			}
			serviceAccountKey, err := flagSecret(cmd, "service-account-key")
			if err != nil {
				return err
			}
			body := sdk.NewGcpCollectionDataStoreIn(deploymentId, bucketName, serviceAccountKey)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.GcpCollectionDataStoreIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "bucket_name")
		},
	}
	cmd.Flags().String("deployment-id", "", "Deployment to register the data store on. It must already hold an unregistered Cloud Storage data store.")
	_ = cmd.MarkFlagRequired("deployment-id")
	cmd.Flags().String("bucket-name", "", "Name of the Cloud Storage bucket Monte Carlo should use.")
	_ = cmd.MarkFlagRequired("bucket-name")
	cmd.Flags().String("service-account-key", "", "Service account key Monte Carlo reaches the bucket with, as the contents of the JSON key file Google issued for it. It replaces the stored key rather than merging into it. Visible in the process list; --service-account-key-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("service-account-key-prompt", false, "Read --service-account-key from a hidden prompt instead of the command line.")
	cmd.Flags().String("name", "", "Display name for the data store. Replaces the name its deployment gave it.")
	return cmd
}

func newCollectionDataStoresUpdateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update collection data store",
	}
	cmd.AddCommand(newCollectionDataStoresUpdateAwsCmd())
	cmd.AddCommand(newCollectionDataStoresUpdateAzureCmd())
	cmd.AddCommand(newCollectionDataStoresUpdateGcpCmd())
	return cmd
}

func newCollectionDataStoresUpdateAwsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws <collection_data_store_id>",
		Short: "Update an AWS collection data store",
		Long:  "Change the bucket, the role or the name of an S3 data store.\n\nSend any of the three. Anything you leave out is kept as it is. A data store with no bucket\nyet needs one supplied here.\n\nA new bucket or role is checked before it is saved, and re-enables a data store that had\nbeen disabled. Nothing changes if that check fails. Sending only `name` skips the check.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.UpdateAwsCollectionDataStore(ctx, args[0])
			body := sdk.NewAwsCollectionDataStorePatch()
			if changed(cmd, "bucket-name") {
				bucketName, err := flagString(cmd, "bucket-name")
				if err != nil {
					return err
				}
				body.SetBucketName(bucketName)
			}
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "role-arn") {
				roleArn, err := flagString(cmd, "role-arn")
				if err != nil {
					return err
				}
				body.SetRoleArn(roleArn)
			}
			req = req.AwsCollectionDataStorePatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "bucket_name", "external_id")
		},
	}
	cmd.Flags().String("bucket-name", "", "Name of the S3 bucket Monte Carlo should use.")
	cmd.Flags().String("name", "", "Display name for the data store. Replaces the name its deployment gave it.")
	cmd.Flags().String("role-arn", "", "ARN of the role Monte Carlo assumes to access the bucket. Its trust policy must already carry the deployment's external id.")
	return cmd
}

func newCollectionDataStoresUpdateAzureCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure <collection_data_store_id>",
		Short: "Update an Azure collection data store",
		Long:  "Change the container, the credentials, the authentication type or the name.\n\nSend any of them. Anything you leave out is kept as it is. A data store with no container\nyet needs one supplied here.\n\nA credentials object replaces the stored credentials rather than merging into them, so send\nevery field of it, along with the `authentication_type` it belongs to. That is also how you\nmove a data store between the two authentication types.\n\nAnything Monte Carlo validates against your storage is checked before it is saved, and\nre-enables a data store that had been disabled. Nothing changes if that check fails. Sending\nonly `name` skips the check.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.UpdateAzureCollectionDataStore(ctx, args[0])
			body := sdk.NewAzureCollectionDataStorePatch()
			if changed(cmd, "authentication-type") {
				authenticationTypeValue, err := flagString(cmd, "authentication-type")
				if err != nil {
					return err
				}
				authenticationType, err := sdk.NewAzureDataStoreAuthenticationTypeFromValue(authenticationTypeValue)
				if err != nil {
					return err
				}
				body.SetAuthenticationType(*authenticationType)
			}
			if changed(cmd, "container-name") {
				containerName, err := flagString(cmd, "container-name")
				if err != nil {
					return err
				}
				body.SetContainerName(containerName)
			}
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "service-principal-tenant-id", "service-principal-client-id", "service-principal-client-secret", "service-principal-client-secret-prompt", "service-principal-account-url", "service-principal-account-name") {
				if err := requireAny(cmd, "service-principal-tenant-id"); err != nil {
					return err
				}
				servicePrincipalTenantId, err := flagString(cmd, "service-principal-tenant-id")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-client-id"); err != nil {
					return err
				}
				servicePrincipalClientId, err := flagString(cmd, "service-principal-client-id")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-client-secret", "service-principal-client-secret-prompt"); err != nil {
					return err
				}
				servicePrincipalClientSecret, err := flagSecret(cmd, "service-principal-client-secret")
				if err != nil {
					return err
				}
				if err := requireAny(cmd, "service-principal-account-url"); err != nil {
					return err
				}
				servicePrincipalAccountUrl, err := flagString(cmd, "service-principal-account-url")
				if err != nil {
					return err
				}
				nested := sdk.NewStorageServicePrincipalCredentialsIn(servicePrincipalTenantId, servicePrincipalClientId, servicePrincipalClientSecret, servicePrincipalAccountUrl)
				if changed(cmd, "service-principal-account-name") {
					servicePrincipalAccountName, err := flagString(cmd, "service-principal-account-name")
					if err != nil {
						return err
					}
					nested.SetAccountName(servicePrincipalAccountName)
				}
				body.SetServicePrincipal(*nested)
			}
			if changed(cmd, "storage-account-keys-connection-string", "storage-account-keys-connection-string-prompt") {
				if err := requireAny(cmd, "storage-account-keys-connection-string", "storage-account-keys-connection-string-prompt"); err != nil {
					return err
				}
				storageAccountKeysConnectionString, err := flagSecret(cmd, "storage-account-keys-connection-string")
				if err != nil {
					return err
				}
				nested := sdk.NewStorageAccountKeysCredentialsIn(storageAccountKeysConnectionString)
				body.SetStorageAccountKeys(*nested)
			}
			req = req.AzureCollectionDataStorePatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "container_name")
		},
	}
	cmd.Flags().String("authentication-type", "", "How Monte Carlo authenticates to the storage account. Send it together with the matching credentials object.")
	_ = cmd.RegisterFlagCompletionFunc("authentication-type", enumCompletion(sdk.AllowedAzureDataStoreAuthenticationTypeEnumValues))
	cmd.Flags().String("container-name", "", "Name of the blob container Monte Carlo should use.")
	cmd.Flags().String("name", "", "Display name for the data store. Replaces the name its deployment gave it.")
	cmd.Flags().String("service-principal-tenant-id", "", "Directory (tenant) id the service principal lives in.")
	cmd.Flags().String("service-principal-client-id", "", "Application (client) id of the service principal.")
	cmd.Flags().String("service-principal-client-secret", "", "Client secret of the service principal. Visible in the process list; --service-principal-client-secret-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("service-principal-client-secret-prompt", false, "Read --service-principal-client-secret from a hidden prompt instead of the command line.")
	cmd.Flags().String("service-principal-account-url", "", "URL of the storage account Monte Carlo sends requests to. A private endpoint or a custom host works, so this is not required to be under blob.core.windows.net.")
	cmd.Flags().String("service-principal-account-name", "", "Name of the storage account, needed only when account_url does not start with it. Monte Carlo takes the first label of the host otherwise, which is right for a standard or private-link URL but not for a custom ingress host.")
	cmd.Flags().String("storage-account-keys-connection-string", "", "Connection string for the storage account holding the container. It carries the account key, so treat it as a secret. Visible in the process list; --storage-account-keys-connection-string-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("storage-account-keys-connection-string-prompt", false, "Read --storage-account-keys-connection-string from a hidden prompt instead of the command line.")
	return cmd
}

func newCollectionDataStoresUpdateGcpCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp <collection_data_store_id>",
		Short: "Update a GCP collection data store",
		Long:  "Change the bucket, the service account key or the name.\n\nSend any of them. Anything you leave out is kept as it is. A data store with no bucket yet\nneeds one supplied here.\n\nThe service account key replaces the stored key rather than merging into it.\n\nAnything Monte Carlo validates against your storage is checked before it is saved, and\nre-enables a data store that had been disabled. Nothing changes if that check fails. Sending\nonly `name` skips the check.\n\nAn id that names a data store on another platform, or no data store in your account,\nreturns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CollectionDataStoresAPI.UpdateGcpCollectionDataStore(ctx, args[0])
			body := sdk.NewGcpCollectionDataStorePatch()
			if changed(cmd, "bucket-name") {
				bucketName, err := flagString(cmd, "bucket-name")
				if err != nil {
					return err
				}
				body.SetBucketName(bucketName)
			}
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			if changed(cmd, "service-account-key", "service-account-key-prompt") {
				serviceAccountKey, err := flagSecret(cmd, "service-account-key")
				if err != nil {
					return err
				}
				body.SetServiceAccountKey(serviceAccountKey)
			}
			req = req.GcpCollectionDataStorePatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "deployment_id", "storage_type", "authentication_type", "enabled", "created_time", "last_updated_time", "bucket_name")
		},
	}
	cmd.Flags().String("bucket-name", "", "Name of the Cloud Storage bucket Monte Carlo should use.")
	cmd.Flags().String("name", "", "Display name for the data store. Replaces the name its deployment gave it.")
	cmd.Flags().String("service-account-key", "", "Service account key Monte Carlo reaches the bucket with, as the contents of the JSON key file Google issued for it. It replaces the stored key rather than merging into it. Visible in the process list; --service-account-key-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("service-account-key-prompt", false, "Read --service-account-key from a hidden prompt instead of the command line.")
	return cmd
}
