// Code generated by api-codegen; DO NOT EDIT.

package cmd

import (
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(newConnectionTypesCmd())
}

func newConnectionTypesCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "connection-types",
		Short: "Connection types",
	}
	cmd.AddCommand(newConnectionTypesListCmd())
	return cmd
}

func newConnectionTypesListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List connection types",
		Long:  "List the connection types your account can add a connection of, by connection type.\n\nEach entry says what the connection is added to, where its credentials can be kept, and\nwhether it runs through a deployment. A type your plan does not include is not listed.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.ConnectionTypesAPI.ListConnectionTypes(ctx)
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderList(cmd, out, []string{"connection_type", "name", "parent", "credentials_required", "requires_deployment"})
		},
	}
	return cmd
}
