// Code generated by api-codegen; DO NOT EDIT.

package cmd

import (
	"net/http"

	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newConnectionsCmd())
}

func newConnectionsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "connections",
		Short: "Connections",
	}
	cmd.AddCommand(newConnectionsCreateCmd())
	cmd.AddCommand(newConnectionsDeleteCmd())
	cmd.AddCommand(newConnectionsGetCmd())
	cmd.AddCommand(newConnectionsListCmd())
	cmd.AddCommand(newConnectionsUpdateCmd())
	cmd.AddCommand(newConnectionsValidateConnectionCmd())
	return cmd
}

func newConnectionsCreateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a connection",
		Long:  "Add a connection to a warehouse.\n\nCreate the credentials first, through one of the credentials endpoints, then name them\nhere. The connection's type comes from them, and has to be a type the warehouse accepts\nand the warehouse's deployment supports.\n\nOmit `job_types` to run what the type runs by default.\n\nAn unknown warehouse id or credentials id returns 404.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.ConnectionsAPI.CreateConnection(ctx)
			name, err := flagString(cmd, "name")
			if err != nil {
				return err
			}
			warehouseId, err := flagString(cmd, "warehouse-id")
			if err != nil {
				return err
			}
			credentialsId, err := flagString(cmd, "credentials-id")
			if err != nil {
				return err
			}
			body := sdk.NewConnectionIn(name, warehouseId, credentialsId)
			if changed(cmd, "job-types") {
				jobTypes, err := flagStringSlice(cmd, "job-types")
				if err != nil {
					return err
				}
				body.SetJobTypes(jobTypes)
			}
			req = req.ConnectionIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "name", "warehouse_id", "warehouse_name", "deployment_id", "deployment_name", "credentials_id", "credentials_storage_type", "job_types", "created_time")
		},
	}
	cmd.Flags().String("name", "", "Display name for the connection. Unique among the warehouse's connections.")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().String("warehouse-id", "", "The warehouse to add the connection to. Its type has to match what the credentials are for.")
	_ = cmd.MarkFlagRequired("warehouse-id")
	cmd.Flags().String("credentials-id", "", "The credentials the connection reads with. They also decide the connection's type. Create them first, through one of the credentials endpoints.")
	_ = cmd.MarkFlagRequired("credentials-id")
	cmd.Flags().StringSlice("job-types", nil, "The jobs to run on this connection. Omit it to run what the connection type runs by default, which is what the app does. Which values are accepted depends on the connection type. An empty list is not accepted; omit the field to take the defaults.")
	return cmd
}

func newConnectionsDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <connection_id>",
		Short: "Delete a connection",
		Long:  "Delete a connection.\n\nThe warehouse and the credentials are left in place. Delete each of those through its own\nendpoint once nothing uses it. Deleting the connection also deletes its own schedules,\nmonitors and rules.\n\nDeleting a warehouse's last connection is refused when that would also take monitors,\nrules or use cases that belong to the warehouse as a whole. Delete the warehouse instead.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete connection"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.ConnectionsAPI.DeleteConnection(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newConnectionsGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <connection_id>",
		Short: "Get a connection",
		Long:  "Get one connection.\n\nAn id that does not exist, belongs to another account, or names a connection your domain\nrestrictions hide from you returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.ConnectionsAPI.GetConnection(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "name", "warehouse_id", "warehouse_name", "deployment_id", "deployment_name", "credentials_id", "credentials_storage_type", "job_types", "created_time")
		},
	}
	return cmd
}

func newConnectionsListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List connections",
		Long:  "List the connections in your account, a page at a time.\n\nConnections are returned oldest first. Pass `warehouse_id` to list one warehouse's\nconnections; an id you cannot see returns an empty page. A caller whose asset access is\nrestricted to certain domains sees only the connections of warehouses holding assets in\nthose domains.\n\nConnections that belong to a BI or ETL integration rather than to a warehouse are not\nlisted here.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.ConnectionsAPI.ListConnections(ctx)
			if changed(cmd, "warehouse-id") {
				warehouseId, err := flagString(cmd, "warehouse-id")
				if err != nil {
					return err
				}
				req = req.WarehouseId(warehouseId)
			}
			if changed(cmd, "cursor") {
				cursor, err := flagString(cmd, "cursor")
				if err != nil {
					return err
				}
				req = req.Cursor(cursor)
			}
			if changed(cmd, "limit") {
				limit, err := flagInt(cmd, "limit")
				if err != nil {
					return err
				}
				req = req.Limit(limit)
			}
			if changed(cmd, "with-count") {
				withCount, err := flagBool(cmd, "with-count")
				if err != nil {
					return err
				}
				req = req.WithCount(withCount)
			}
			if !changed(cmd, "cursor", "limit", "with-count") {
				return renderPages(cmd, []string{"id", "name", "connection_type", "warehouse_name", "deployment_name"}, func(cursor string) (any, *http.Response, error) {
					r := req
					if cursor != "" {
						r = r.Cursor(cursor)
					}
					return r.Execute()
				})
			}
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderPage(cmd, out, []string{"id", "name", "connection_type", "warehouse_name", "deployment_name"})
		},
	}
	cmd.Flags().String("warehouse-id", "", "Only list connections on this warehouse. Omit it to list every connection in your account.")
	cmd.Flags().String("cursor", "", "Position to continue from, as returned in next_cursor by the previous page. Omit it to start from the first page. The value is opaque; do not build or modify one.")
	cmd.Flags().Int32("limit", 0, "Maximum number of items to return, between 1 and 100.")
	cmd.Flags().Bool("with-count", false, "Whether to also return the total number of items across every page, in count. Off by default: counting costs an extra query.")
	return cmd
}

func newConnectionsUpdateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update <connection_id>",
		Short: "Update a connection",
		Long:  "Rename a connection.\n\nThe name is the only thing you can change. The type, the warehouse and the credentials\nare fixed when the connection is created. Two connections on one warehouse cannot share a\nname. Sending an empty body leaves the connection as it is and returns it.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.ConnectionsAPI.UpdateConnection(ctx, args[0])
			body := sdk.NewConnectionPatch()
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.ConnectionPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "name", "warehouse_id", "warehouse_name", "deployment_id", "deployment_name", "credentials_id", "credentials_storage_type", "job_types", "created_time")
		},
	}
	cmd.Flags().String("name", "", "New display name for the connection. Omit it to leave the name unchanged. An explicit null is ignored, the same as omitting the field.")
	return cmd
}

func newConnectionsValidateConnectionCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "validate-connection <connection_id>",
		Short: "Validate a connection",
		Long:  "Check a connection against the system it reads from.\n\nTests the connection as it stands, with the credentials it already uses. Nothing is\nchanged, and you send no credentials.\n\nThe response is the run as it starts, and `Location` names where to read it. Poll that\nuntil the run's status is `completed`; each validation carries its own verdict.\n\nAn id that does not exist or belongs to another account returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.ConnectionsAPI.ValidateConnection(ctx, args[0])
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "status", "target_type", "target_id", "validations_passed", "validations_total", "started_at", "finished_at", "expires_at", "validations")
		},
	}
	return cmd
}
