// Code generated by api-codegen; DO NOT EDIT.
package cmd

import (
	"net/http"

	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newCredentialsCmd())
}

func newCredentialsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "credentials",
		Short: "Credentials",
	}
	cmd.AddCommand(newCredentialsCreateCmd())
	cmd.AddCommand(newCredentialsDeleteCmd())
	cmd.AddCommand(newCredentialsGetCmd())
	cmd.AddCommand(newCredentialsListCmd())
	cmd.AddCommand(newCredentialsUpdateCmd())
	return cmd
}

func newCredentialsCreateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create credential",
	}
	cmd.AddCommand(newCredentialsCreateAwsSecretsManagerCmd())
	cmd.AddCommand(newCredentialsCreateAzureKeyVaultCmd())
	cmd.AddCommand(newCredentialsCreateEnvVarCmd())
	cmd.AddCommand(newCredentialsCreateFileCmd())
	cmd.AddCommand(newCredentialsCreateGcpSecretManagerCmd())
	cmd.AddCommand(newCredentialsCreateSnowflakeCmd())
	return cmd
}

func newCredentialsCreateAwsSecretsManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws-secrets-manager",
		Short: "Create AWS Secrets Manager credentials",
		Long:  "Store where a connection's credentials live in your AWS Secrets Manager.\n\nMonte Carlo keeps the reference, not the secret, and reads the secret from your store each\ntime the connection is used. Create the credentials first, then create a connection that\nreferences them. Nothing is checked against AWS here.\n\n`connection_type` names what the secret holds credentials for, and is fixed once created.\nAn account holds a limited number of credentials; past that the create is refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.CreateAwsSecretsManagerCredentials(ctx)
			connectionType, err := flagString(cmd, "connection-type")
			if err != nil {
				return err
			}
			awsSecret, err := flagString(cmd, "aws-secret")
			if err != nil {
				return err
			}
			body := sdk.NewAwsSecretsManagerCredentialsIn(connectionType, awsSecret)
			if changed(cmd, "assumable-role") {
				assumableRole, err := flagString(cmd, "assumable-role")
				if err != nil {
					return err
				}
				body.SetAssumableRole(assumableRole)
			}
			if changed(cmd, "aws-region") {
				awsRegion, err := flagString(cmd, "aws-region")
				if err != nil {
					return err
				}
				body.SetAwsRegion(awsRegion)
			}
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			if changed(cmd, "external-id") {
				externalId, err := flagString(cmd, "external-id")
				if err != nil {
					return err
				}
				body.SetExternalId(externalId)
			}
			req = req.AwsSecretsManagerCredentialsIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "aws_secret", "aws_region", "assumable_role", "external_id")
		},
	}
	cmd.Flags().String("connection-type", "", "The connection type the credentials are for, such as snowflake or bigquery, or one of your custom connector types. Fixed once created.")
	_ = cmd.MarkFlagRequired("connection-type")
	cmd.Flags().String("aws-secret", "", "Name or ARN of the AWS Secrets Manager secret holding the connection's credentials.")
	_ = cmd.MarkFlagRequired("aws-secret")
	cmd.Flags().String("assumable-role", "", "ARN of a role the deployment assumes to read the secret. Omit it to read as itself.")
	cmd.Flags().String("aws-region", "", "AWS region of the secret. Omit it to use the deployment's own region.")
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	cmd.Flags().String("external-id", "", "External id the assumed role's trust policy requires, if it requires one.")
	return cmd
}

func newCredentialsCreateAzureKeyVaultCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure-key-vault",
		Short: "Create Azure Key Vault credentials",
		Long:  "Store where a connection's credentials live in your Azure Key Vault.\n\nMonte Carlo keeps the reference, not the secret, and reads the secret from your store each\ntime the connection is used. Name the vault by `akv_vault_name`, `akv_vault_url`, or both.\nCreate the credentials first, then create a connection that references them. Nothing is\nchecked against Azure here.\n\n`connection_type` names what the secret holds credentials for, and is fixed once created.\nAn account holds a limited number of credentials; past that the create is refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.CreateAzureKeyVaultCredentials(ctx)
			connectionType, err := flagString(cmd, "connection-type")
			if err != nil {
				return err
			}
			akvSecret, err := flagString(cmd, "akv-secret")
			if err != nil {
				return err
			}
			body := sdk.NewAzureKeyVaultCredentialsIn(connectionType, akvSecret)
			if changed(cmd, "akv-vault-name") {
				akvVaultName, err := flagString(cmd, "akv-vault-name")
				if err != nil {
					return err
				}
				body.SetAkvVaultName(akvVaultName)
			}
			if changed(cmd, "akv-vault-url") {
				akvVaultUrl, err := flagString(cmd, "akv-vault-url")
				if err != nil {
					return err
				}
				body.SetAkvVaultUrl(akvVaultUrl)
			}
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			req = req.AzureKeyVaultCredentialsIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "akv_secret", "akv_vault_name", "akv_vault_url")
		},
	}
	cmd.Flags().String("connection-type", "", "The connection type the credentials are for, such as snowflake or bigquery, or one of your custom connector types. Fixed once created.")
	_ = cmd.MarkFlagRequired("connection-type")
	cmd.Flags().String("akv-secret", "", "Name of the Azure Key Vault secret holding the connection's credentials.")
	_ = cmd.MarkFlagRequired("akv-secret")
	cmd.Flags().String("akv-vault-name", "", "Name of the key vault. Send this, akv_vault_url, or both.")
	cmd.Flags().String("akv-vault-url", "", "URL of the key vault. Send this, akv_vault_name, or both.")
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	return cmd
}

func newCredentialsCreateEnvVarCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "env-var",
		Short: "Create environment variable credentials",
		Long:  "Store which environment variable of your deployment holds a connection's credentials.\n\nMonte Carlo keeps the variable's name, not its value, and reads the value on the deployment\neach time the connection is used. The name has to start with `MCD_`. A value encrypted with\nAWS KMS is decrypted with the key `kms_key_id` names. Create the credentials first, then\ncreate a connection that references them. Nothing is checked on the deployment here.\n\n`connection_type` names what the variable holds credentials for, and is fixed once created.\nAn account holds a limited number of credentials; past that the create is refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.CreateEnvVarCredentials(ctx)
			connectionType, err := flagString(cmd, "connection-type")
			if err != nil {
				return err
			}
			envVarName, err := flagString(cmd, "env-var-name")
			if err != nil {
				return err
			}
			body := sdk.NewEnvVarCredentialsIn(connectionType, envVarName)
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			if changed(cmd, "kms-key-id") {
				kmsKeyId, err := flagString(cmd, "kms-key-id")
				if err != nil {
					return err
				}
				body.SetKmsKeyId(kmsKeyId)
			}
			req = req.EnvVarCredentialsIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "env_var_name", "kms_key_id")
		},
	}
	cmd.Flags().String("connection-type", "", "The connection type the credentials are for, such as snowflake or bigquery, or one of your custom connector types. Fixed once created.")
	_ = cmd.MarkFlagRequired("connection-type")
	cmd.Flags().String("env-var-name", "", "Name of the environment variable on the deployment that holds the connection's credentials. Must start with MCD_.")
	_ = cmd.MarkFlagRequired("env-var-name")
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	cmd.Flags().String("kms-key-id", "", "AWS KMS key the variable's value is encrypted with. Omit it for a value stored in the clear.")
	return cmd
}

func newCredentialsCreateFileCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "file",
		Short: "Create file credentials",
		Long:  "Store which file on your deployment holds a connection's credentials.\n\nMonte Carlo keeps the path, not the contents, and reads the file on the deployment each\ntime the connection is used. Create the credentials first, then create a connection that\nreferences them. Nothing is checked on the deployment here.\n\n`connection_type` names what the file holds credentials for, and is fixed once created. An\naccount holds a limited number of credentials; past that the create is refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.CreateFileCredentials(ctx)
			connectionType, err := flagString(cmd, "connection-type")
			if err != nil {
				return err
			}
			filePath, err := flagString(cmd, "file-path")
			if err != nil {
				return err
			}
			body := sdk.NewFileCredentialsIn(connectionType, filePath)
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			req = req.FileCredentialsIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "file_path")
		},
	}
	cmd.Flags().String("connection-type", "", "The connection type the credentials are for, such as snowflake or bigquery, or one of your custom connector types. Fixed once created.")
	_ = cmd.MarkFlagRequired("connection-type")
	cmd.Flags().String("file-path", "", "Path of the file on the deployment that holds the connection's credentials.")
	_ = cmd.MarkFlagRequired("file-path")
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	return cmd
}

func newCredentialsCreateGcpSecretManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp-secret-manager",
		Short: "Create GCP Secret Manager credentials",
		Long:  "Store where a connection's credentials live in your GCP Secret Manager.\n\nMonte Carlo keeps the reference, not the secret, and reads the secret from your store each\ntime the connection is used. Create the credentials first, then create a connection that\nreferences them. Nothing is checked against GCP here.\n\n`connection_type` names what the secret holds credentials for, and is fixed once created.\nAn account holds a limited number of credentials; past that the create is refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.CreateGcpSecretManagerCredentials(ctx)
			connectionType, err := flagString(cmd, "connection-type")
			if err != nil {
				return err
			}
			gcpSecret, err := flagString(cmd, "gcp-secret")
			if err != nil {
				return err
			}
			body := sdk.NewGcpSecretManagerCredentialsIn(connectionType, gcpSecret)
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			req = req.GcpSecretManagerCredentialsIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "gcp_secret")
		},
	}
	cmd.Flags().String("connection-type", "", "The connection type the credentials are for, such as snowflake or bigquery, or one of your custom connector types. Fixed once created.")
	_ = cmd.MarkFlagRequired("connection-type")
	cmd.Flags().String("gcp-secret", "", "Name of the GCP Secret Manager secret holding the connection's credentials.")
	_ = cmd.MarkFlagRequired("gcp-secret")
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	return cmd
}

func newCredentialsCreateSnowflakeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "snowflake",
		Short: "Create Snowflake credentials",
		Long:  "Store a Snowflake key pair for connections to use.\n\nMonte Carlo keeps the private key and returns only the account, user and warehouse. Create\nthe credentials first, then create a connection that references them. Nothing is checked\nagainst Snowflake here.\n\nAn account holds a limited number of credentials; past that the create is refused.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := requireAny(cmd, "private-key", "private-key-prompt"); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.CreateSnowflakeCredentials(ctx)
			account, err := flagString(cmd, "account")
			if err != nil {
				return err
			}
			user, err := flagString(cmd, "user")
			if err != nil {
				return err
			}
			privateKey, err := flagSecret(cmd, "private-key")
			if err != nil {
				return err
			}
			body := sdk.NewSnowflakeCredentialsIn(account, user, privateKey)
			if changed(cmd, "private-key-passphrase", "private-key-passphrase-prompt") {
				privateKeyPassphrase, err := flagSecret(cmd, "private-key-passphrase")
				if err != nil {
					return err
				}
				body.SetPrivateKeyPassphrase(privateKeyPassphrase)
			}
			if changed(cmd, "warehouse") {
				warehouse, err := flagString(cmd, "warehouse")
				if err != nil {
					return err
				}
				body.SetWarehouse(warehouse)
			}
			req = req.SnowflakeCredentialsIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "account", "user", "warehouse")
		},
	}
	cmd.Flags().String("account", "", "Snowflake account identifier, such as xy12345.us-east-1. Without the .snowflakecomputing.com suffix.")
	_ = cmd.MarkFlagRequired("account")
	cmd.Flags().String("user", "", "Snowflake user the key pair belongs to.")
	_ = cmd.MarkFlagRequired("user")
	cmd.Flags().String("private-key", "", "The private key of the pair, as PEM text including its BEGIN and END lines. Stored by Monte Carlo and never returned. Visible in the process list; --private-key-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("private-key-prompt", false, "Read --private-key from a hidden prompt instead of the command line.")
	cmd.Flags().String("private-key-passphrase", "", "Passphrase the private key is encrypted with. Omit it for an unencrypted key. Never returned. Visible in the process list; --private-key-passphrase-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("private-key-passphrase-prompt", false, "Read --private-key-passphrase from a hidden prompt instead of the command line.")
	cmd.Flags().String("warehouse", "", "Snowflake virtual warehouse to run queries in. Omit it to use the user's default.")
	return cmd
}

func newCredentialsDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete credential",
	}
	cmd.AddCommand(newCredentialsDeleteAwsSecretsManagerCmd())
	cmd.AddCommand(newCredentialsDeleteAzureKeyVaultCmd())
	cmd.AddCommand(newCredentialsDeleteEnvVarCmd())
	cmd.AddCommand(newCredentialsDeleteFileCmd())
	cmd.AddCommand(newCredentialsDeleteGcpSecretManagerCmd())
	cmd.AddCommand(newCredentialsDeleteSnowflakeCmd())
	return cmd
}

func newCredentialsDeleteAwsSecretsManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws-secrets-manager <credentials_id>",
		Short: "Delete AWS Secrets Manager credentials",
		Long:  "Delete AWS Secrets Manager credentials.\n\nRefused while a connection still uses them: delete the connection or point it at other\ncredentials first. The secret in AWS is untouched.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete aws-secrets-manager credential"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.DeleteAwsSecretsManagerCredentials(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCredentialsDeleteAzureKeyVaultCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure-key-vault <credentials_id>",
		Short: "Delete Azure Key Vault credentials",
		Long:  "Delete Azure Key Vault credentials.\n\nRefused while a connection still uses them: delete the connection or point it at other\ncredentials first. The secret in Azure is untouched.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete azure-key-vault credential"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.DeleteAzureKeyVaultCredentials(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCredentialsDeleteEnvVarCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "env-var <credentials_id>",
		Short: "Delete environment variable credentials",
		Long:  "Delete environment variable credentials.\n\nRefused while a connection still uses them: delete the connection or point it at other\ncredentials first. The variable on the deployment is untouched.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete env-var credential"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.DeleteEnvVarCredentials(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCredentialsDeleteFileCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "file <credentials_id>",
		Short: "Delete file credentials",
		Long:  "Delete file credentials.\n\nRefused while a connection still uses them: delete the connection or point it at other\ncredentials first. The file on the deployment is untouched.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete file credential"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.DeleteFileCredentials(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCredentialsDeleteGcpSecretManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp-secret-manager <credentials_id>",
		Short: "Delete GCP Secret Manager credentials",
		Long:  "Delete GCP Secret Manager credentials.\n\nRefused while a connection still uses them: delete the connection or point it at other\ncredentials first. The secret in GCP is untouched.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete gcp-secret-manager credential"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.DeleteGcpSecretManagerCredentials(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCredentialsDeleteSnowflakeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "snowflake <credentials_id>",
		Short: "Delete Snowflake credentials",
		Long:  "Delete Snowflake credentials.\n\nRefused while a connection still uses them: delete the connection or point it at other\ncredentials first. Monte Carlo stops using the stored key. Rotate or revoke the key pair\nin Snowflake if the key itself must be retired.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete snowflake credential"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.DeleteSnowflakeCredentials(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newCredentialsGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get credential",
	}
	cmd.AddCommand(newCredentialsGetAwsSecretsManagerCmd())
	cmd.AddCommand(newCredentialsGetAzureKeyVaultCmd())
	cmd.AddCommand(newCredentialsGetEnvVarCmd())
	cmd.AddCommand(newCredentialsGetFileCmd())
	cmd.AddCommand(newCredentialsGetGcpSecretManagerCmd())
	cmd.AddCommand(newCredentialsGetSnowflakeCmd())
	return cmd
}

func newCredentialsGetAwsSecretsManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws-secrets-manager <credentials_id>",
		Short: "Get AWS Secrets Manager credentials",
		Long:  "Get one set of AWS Secrets Manager credentials.\n\nAn id that does not exist, belongs to another account, or names credentials of another\nkind returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.GetAwsSecretsManagerCredentials(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "aws_secret", "aws_region", "assumable_role", "external_id")
		},
	}
	return cmd
}

func newCredentialsGetAzureKeyVaultCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure-key-vault <credentials_id>",
		Short: "Get Azure Key Vault credentials",
		Long:  "Get one set of Azure Key Vault credentials.\n\nAn id that does not exist, belongs to another account, or names credentials of another\nkind returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.GetAzureKeyVaultCredentials(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "akv_secret", "akv_vault_name", "akv_vault_url")
		},
	}
	return cmd
}

func newCredentialsGetEnvVarCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "env-var <credentials_id>",
		Short: "Get environment variable credentials",
		Long:  "Get one set of environment variable credentials.\n\nAn id that does not exist, belongs to another account, or names credentials of another\nkind returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.GetEnvVarCredentials(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "env_var_name", "kms_key_id")
		},
	}
	return cmd
}

func newCredentialsGetFileCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "file <credentials_id>",
		Short: "Get file credentials",
		Long:  "Get one set of file credentials.\n\nAn id that does not exist, belongs to another account, or names credentials of another\nkind returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.GetFileCredentials(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "file_path")
		},
	}
	return cmd
}

func newCredentialsGetGcpSecretManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp-secret-manager <credentials_id>",
		Short: "Get GCP Secret Manager credentials",
		Long:  "Get one set of GCP Secret Manager credentials.\n\nAn id that does not exist, belongs to another account, or names credentials of another\nkind returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.GetGcpSecretManagerCredentials(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "gcp_secret")
		},
	}
	return cmd
}

func newCredentialsGetSnowflakeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "snowflake <credentials_id>",
		Short: "Get Snowflake credentials",
		Long:  "Get one set of Snowflake credentials, without the key.\n\nAn id that does not exist, belongs to another account, or names credentials of another\nkind returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.GetSnowflakeCredentials(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "account", "user", "warehouse")
		},
	}
	return cmd
}

func newCredentialsListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List credentials",
		Long:  "List the credentials in your account, of every kind, a page at a time.\n\nCredentials are returned oldest first. Each entry says what connection type it is for and\nwhere its secret lives; read the typed endpoint for that kind to see its other fields.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.ListCredentials(ctx)
			if changed(cmd, "cursor") {
				cursor, err := flagString(cmd, "cursor")
				if err != nil {
					return err
				}
				req = req.Cursor(cursor)
			}
			if changed(cmd, "limit") {
				limit, err := flagInt(cmd, "limit")
				if err != nil {
					return err
				}
				req = req.Limit(limit)
			}
			if changed(cmd, "with-count") {
				withCount, err := flagBool(cmd, "with-count")
				if err != nil {
					return err
				}
				req = req.WithCount(withCount)
			}
			if !changed(cmd, "cursor", "limit", "with-count") {
				return renderPages(cmd, []string{"id", "connection_type", "storage_type", "created_time"}, func(cursor string) (any, *http.Response, error) {
					r := req
					if cursor != "" {
						r = r.Cursor(cursor)
					}
					return r.Execute()
				})
			}
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderPage(cmd, out, []string{"id", "connection_type", "storage_type", "created_time"})
		},
	}
	cmd.Flags().String("cursor", "", "Position to continue from, as returned in next_cursor by the previous page. Omit it to start from the first page. The value is opaque; do not build or modify one.")
	cmd.Flags().Int32("limit", 0, "Maximum number of items to return, between 1 and 100.")
	cmd.Flags().Bool("with-count", false, "Whether to also return the total number of items across every page, in count. Off by default: counting costs an extra query.")
	return cmd
}

func newCredentialsUpdateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update credential",
	}
	cmd.AddCommand(newCredentialsUpdateAwsSecretsManagerCmd())
	cmd.AddCommand(newCredentialsUpdateAzureKeyVaultCmd())
	cmd.AddCommand(newCredentialsUpdateEnvVarCmd())
	cmd.AddCommand(newCredentialsUpdateFileCmd())
	cmd.AddCommand(newCredentialsUpdateGcpSecretManagerCmd())
	cmd.AddCommand(newCredentialsUpdateSnowflakeCmd())
	return cmd
}

func newCredentialsUpdateAwsSecretsManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "aws-secrets-manager <credentials_id>",
		Short: "Update AWS Secrets Manager credentials",
		Long:  "Change AWS Secrets Manager credentials in place.\n\nEvery connection using the credentials picks up the change. Send only the fields to\nchange: a field left out is unchanged, and an optional field set to null is cleared.\nSending an empty body returns the credentials as they are.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.UpdateAwsSecretsManagerCredentials(ctx, args[0])
			body := sdk.NewAwsSecretsManagerCredentialsPatch()
			if changed(cmd, "assumable-role") {
				assumableRole, err := flagString(cmd, "assumable-role")
				if err != nil {
					return err
				}
				body.SetAssumableRole(assumableRole)
			}
			if changed(cmd, "aws-region") {
				awsRegion, err := flagString(cmd, "aws-region")
				if err != nil {
					return err
				}
				body.SetAwsRegion(awsRegion)
			}
			if changed(cmd, "aws-secret") {
				awsSecret, err := flagString(cmd, "aws-secret")
				if err != nil {
					return err
				}
				body.SetAwsSecret(awsSecret)
			}
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			if changed(cmd, "external-id") {
				externalId, err := flagString(cmd, "external-id")
				if err != nil {
					return err
				}
				body.SetExternalId(externalId)
			}
			req = req.AwsSecretsManagerCredentialsPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "aws_secret", "aws_region", "assumable_role", "external_id")
		},
	}
	cmd.Flags().String("assumable-role", "", "ARN of a role the deployment assumes to read the secret. Omit it to read as itself.")
	cmd.Flags().String("aws-region", "", "AWS region of the secret. Omit it to use the deployment's own region.")
	cmd.Flags().String("aws-secret", "", "Name or ARN of the AWS Secrets Manager secret holding the connection's credentials.")
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	cmd.Flags().String("external-id", "", "External id the assumed role's trust policy requires, if it requires one.")
	return cmd
}

func newCredentialsUpdateAzureKeyVaultCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "azure-key-vault <credentials_id>",
		Short: "Update Azure Key Vault credentials",
		Long:  "Change Azure Key Vault credentials in place.\n\nEvery connection using the credentials picks up the change. Send only the fields to\nchange: a field left out is unchanged, and an optional field set to null is cleared, as\nlong as the vault stays named one way. Sending an empty body returns the credentials as\nthey are.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.UpdateAzureKeyVaultCredentials(ctx, args[0])
			body := sdk.NewAzureKeyVaultCredentialsPatch()
			if changed(cmd, "akv-secret") {
				akvSecret, err := flagString(cmd, "akv-secret")
				if err != nil {
					return err
				}
				body.SetAkvSecret(akvSecret)
			}
			if changed(cmd, "akv-vault-name") {
				akvVaultName, err := flagString(cmd, "akv-vault-name")
				if err != nil {
					return err
				}
				body.SetAkvVaultName(akvVaultName)
			}
			if changed(cmd, "akv-vault-url") {
				akvVaultUrl, err := flagString(cmd, "akv-vault-url")
				if err != nil {
					return err
				}
				body.SetAkvVaultUrl(akvVaultUrl)
			}
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			req = req.AzureKeyVaultCredentialsPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "akv_secret", "akv_vault_name", "akv_vault_url")
		},
	}
	cmd.Flags().String("akv-secret", "", "Name of the Azure Key Vault secret holding the connection's credentials.")
	cmd.Flags().String("akv-vault-name", "", "Name of the key vault. Send this, akv_vault_url, or both.")
	cmd.Flags().String("akv-vault-url", "", "URL of the key vault. Send this, akv_vault_name, or both.")
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	return cmd
}

func newCredentialsUpdateEnvVarCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "env-var <credentials_id>",
		Short: "Update environment variable credentials",
		Long:  "Change environment variable credentials in place.\n\nEvery connection using the credentials picks up the change. Send only the fields to\nchange: a field left out is unchanged, and an optional field set to null is cleared.\nSending an empty body returns the credentials as they are.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.UpdateEnvVarCredentials(ctx, args[0])
			body := sdk.NewEnvVarCredentialsPatch()
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			if changed(cmd, "env-var-name") {
				envVarName, err := flagString(cmd, "env-var-name")
				if err != nil {
					return err
				}
				body.SetEnvVarName(envVarName)
			}
			if changed(cmd, "kms-key-id") {
				kmsKeyId, err := flagString(cmd, "kms-key-id")
				if err != nil {
					return err
				}
				body.SetKmsKeyId(kmsKeyId)
			}
			req = req.EnvVarCredentialsPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "env_var_name", "kms_key_id")
		},
	}
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	cmd.Flags().String("env-var-name", "", "Name of the environment variable on the deployment that holds the connection's credentials. Must start with MCD_.")
	cmd.Flags().String("kms-key-id", "", "AWS KMS key the variable's value is encrypted with. Omit it for a value stored in the clear.")
	return cmd
}

func newCredentialsUpdateFileCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "file <credentials_id>",
		Short: "Update file credentials",
		Long:  "Change file credentials in place.\n\nEvery connection using the credentials picks up the change. Send only the fields to\nchange: a field left out is unchanged, and an optional field set to null is cleared.\nSending an empty body returns the credentials as they are.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.UpdateFileCredentials(ctx, args[0])
			body := sdk.NewFileCredentialsPatch()
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			if changed(cmd, "file-path") {
				filePath, err := flagString(cmd, "file-path")
				if err != nil {
					return err
				}
				body.SetFilePath(filePath)
			}
			req = req.FileCredentialsPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "file_path")
		},
	}
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	cmd.Flags().String("file-path", "", "Path of the file on the deployment that holds the connection's credentials.")
	return cmd
}

func newCredentialsUpdateGcpSecretManagerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gcp-secret-manager <credentials_id>",
		Short: "Update GCP Secret Manager credentials",
		Long:  "Change GCP Secret Manager credentials in place.\n\nEvery connection using the credentials picks up the change. Send only the fields to\nchange: a field left out is unchanged, and an optional field set to null is cleared.\nSending an empty body returns the credentials as they are.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.UpdateGcpSecretManagerCredentials(ctx, args[0])
			body := sdk.NewGcpSecretManagerCredentialsPatch()
			if changed(cmd, "bq-project-id") {
				bqProjectId, err := flagString(cmd, "bq-project-id")
				if err != nil {
					return err
				}
				body.SetBqProjectId(bqProjectId)
			}
			if changed(cmd, "databricks-warehouse-id") {
				databricksWarehouseId, err := flagString(cmd, "databricks-warehouse-id")
				if err != nil {
					return err
				}
				body.SetDatabricksWarehouseId(databricksWarehouseId)
			}
			if changed(cmd, "gcp-secret") {
				gcpSecret, err := flagString(cmd, "gcp-secret")
				if err != nil {
					return err
				}
				body.SetGcpSecret(gcpSecret)
			}
			req = req.GcpSecretManagerCredentialsPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "bq_project_id", "databricks_warehouse_id", "gcp_secret")
		},
	}
	cmd.Flags().String("bq-project-id", "", "BigQuery project the connection reads from. Only for a BigQuery connection.")
	cmd.Flags().String("databricks-warehouse-id", "", "Databricks SQL warehouse the connection runs queries on. Required for a databricks-sql-warehouse or databricks-metastore-sql-warehouse connection.")
	cmd.Flags().String("gcp-secret", "", "Name of the GCP Secret Manager secret holding the connection's credentials.")
	return cmd
}

func newCredentialsUpdateSnowflakeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "snowflake <credentials_id>",
		Short: "Update Snowflake credentials",
		Long:  "Change Snowflake credentials in place.\n\nEvery connection using the credentials picks up the change. Send only the fields to\nchange: a field left out is unchanged, `warehouse` set to null is cleared, and a new\n`private_key` replaces the whole key pair. Sending an empty body returns the credentials as\nthey are.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CredentialsAPI.UpdateSnowflakeCredentials(ctx, args[0])
			body := sdk.NewSnowflakeCredentialsPatch()
			if changed(cmd, "account") {
				account, err := flagString(cmd, "account")
				if err != nil {
					return err
				}
				body.SetAccount(account)
			}
			if changed(cmd, "private-key", "private-key-prompt") {
				privateKey, err := flagSecret(cmd, "private-key")
				if err != nil {
					return err
				}
				body.SetPrivateKey(privateKey)
			}
			if changed(cmd, "private-key-passphrase", "private-key-passphrase-prompt") {
				privateKeyPassphrase, err := flagSecret(cmd, "private-key-passphrase")
				if err != nil {
					return err
				}
				body.SetPrivateKeyPassphrase(privateKeyPassphrase)
			}
			if changed(cmd, "user") {
				user, err := flagString(cmd, "user")
				if err != nil {
					return err
				}
				body.SetUser(user)
			}
			if changed(cmd, "warehouse") {
				warehouse, err := flagString(cmd, "warehouse")
				if err != nil {
					return err
				}
				body.SetWarehouse(warehouse)
			}
			req = req.SnowflakeCredentialsPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "connection_type", "storage_type", "created_time", "account", "user", "warehouse")
		},
	}
	cmd.Flags().String("account", "", "New Snowflake account identifier, without the .snowflakecomputing.com suffix.")
	cmd.Flags().String("private-key", "", "New private key, as PEM text. Replaces the stored key and its passphrase; send private_key_passphrase in the same request if the new key has one. Visible in the process list; --private-key-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("private-key-prompt", false, "Read --private-key from a hidden prompt instead of the command line.")
	cmd.Flags().String("private-key-passphrase", "", "Passphrase of the new private key. Only accepted together with private_key. Visible in the process list; --private-key-passphrase-prompt asks for it instead, and @<path> reads it from a file.")
	cmd.Flags().Bool("private-key-passphrase-prompt", false, "Read --private-key-passphrase from a hidden prompt instead of the command line.")
	cmd.Flags().String("user", "", "New Snowflake user.")
	cmd.Flags().String("warehouse", "", "New Snowflake virtual warehouse. An explicit null clears it; queries then run in the user's default.")
	return cmd
}
