// Code generated by api-codegen; DO NOT EDIT.

package cmd

import (
	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newCustomConnectorTypesCmd())
}

func newCustomConnectorTypesCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "custom-connector-types",
		Short: "Custom connector types",
	}
	cmd.AddCommand(newCustomConnectorTypesGetCmd())
	cmd.AddCommand(newCustomConnectorTypesListCmd())
	return cmd
}

func newCustomConnectorTypesGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <custom_connector_type_id>",
		Short: "Get a custom connector type",
		Long:  "Get one custom connector type.\n\nAn id that does not exist or belongs to another account returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CustomConnectorTypesAPI.GetCustomConnectorType(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "asset_class", "collection_agent_id", "deployment_id", "job_types", "icon_url", "terminology", "capabilities", "created_time", "updated_time")
		},
	}
	return cmd
}

func newCustomConnectorTypesListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List custom connector types",
		Long:  "List the custom connector types your collection agents registered, oldest first.\n\nA type whose collection agent was removed outright is not listed.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.CustomConnectorTypesAPI.ListCustomConnectorTypes(ctx)
			if changed(cmd, "asset-class") {
				assetClassValue, err := flagString(cmd, "asset-class")
				if err != nil {
					return err
				}
				assetClass, err := sdk.NewCustomConnectorAssetClassFromValue(assetClassValue)
				if err != nil {
					return usageError("%w", err)
				}
				req = req.AssetClass(*assetClass)
			}
			if changed(cmd, "collection-agent-id") {
				collectionAgentId, err := flagString(cmd, "collection-agent-id")
				if err != nil {
					return err
				}
				req = req.CollectionAgentId(collectionAgentId)
			}
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderList(cmd, out, []string{"id", "name", "asset_class", "deployment_id"})
		},
	}
	cmd.Flags().String("asset-class", "", "Only connector types of this asset class.")
	_ = cmd.RegisterFlagCompletionFunc("asset-class", enumCompletion(sdk.AllowedCustomConnectorAssetClassEnumValues))
	cmd.Flags().String("collection-agent-id", "", "Only connector types this collection agent registered.")
	return cmd
}
