// Code generated by api-codegen; DO NOT EDIT.

package cmd

import (
	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newDeploymentsCmd())
}

func newDeploymentsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "deployments",
		Short: "Deployments",
	}
	cmd.AddCommand(newDeploymentsCreateCmd())
	cmd.AddCommand(newDeploymentsDeleteCmd())
	cmd.AddCommand(newDeploymentsGetCmd())
	cmd.AddCommand(newDeploymentsListCmd())
	cmd.AddCommand(newDeploymentsReprovisionCmd())
	cmd.AddCommand(newDeploymentsUpdateCmd())
	return cmd
}

func newDeploymentsCreateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a deployment",
		Long:  "Provision a deployment for a collection agent or a data store to be registered on.\n\nConnecting either one takes two calls, and this is the first. Monte Carlo allocates the\ndeployment, and returns an external id for a deployment it will reach by assuming a role.\nRegistering on the deployment is the second call, and that is what enables it.\n\nThe new deployment is not enabled and serves no connections until something is registered\non it. It counts against your account's deployment limit as soon as it is created, whether\nor not anything ever is.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.DeploymentsAPI.CreateDeployment(ctx)
			typeValue, err := flagString(cmd, "type")
			if err != nil {
				return err
			}
			type_, err := sdk.NewDeploymentTypeFromValue(typeValue)
			if err != nil {
				return err
			}
			runtimePlatformValue, err := flagString(cmd, "runtime-platform")
			if err != nil {
				return err
			}
			runtimePlatform, err := sdk.NewRuntimePlatformFromValue(runtimePlatformValue)
			if err != nil {
				return err
			}
			body := sdk.NewDeploymentIn(*type_, *runtimePlatform)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.DeploymentIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "type", "runtime_platform", "enabled", "created_time", "last_updated_time", "aws_external_id")
		},
	}
	cmd.Flags().String("type", "", "What the deployment will host. Only COLLECTION_AGENT and COLLECTION_DATA_STORE can be provisioned today. Any other value is rejected.")
	_ = cmd.RegisterFlagCompletionFunc("type", enumCompletion(sdk.AllowedDeploymentTypeEnumValues))
	_ = cmd.MarkFlagRequired("type")
	cmd.Flags().String("runtime-platform", "", "Where the deployment's collection agent or data store will run. Either can be provisioned on AWS, AZURE or GCP, and a collection agent also on GENERIC. Any other combination is rejected.")
	_ = cmd.RegisterFlagCompletionFunc("runtime-platform", enumCompletion(sdk.AllowedRuntimePlatformEnumValues))
	_ = cmd.MarkFlagRequired("runtime-platform")
	cmd.Flags().String("name", "", "Display name for the deployment. Monte Carlo generates one if you leave it out.")
	return cmd
}

func newDeploymentsDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <deployment_id>",
		Short: "Delete a deployment",
		Long:  "Delete a deployment, releasing the infrastructure Monte Carlo runs for it.\n\nThe deployment's storage is deleted with it, so empty that storage first. A deployment\nwith an enabled collection agent or data store, connections still running through it, or\nETL containers on it, cannot be deleted. Neither can one hosted by Monte Carlo, which this\nAPI does not provision. One that is not enabled is deleted along with the deployment.\n\nDeleting reaches several systems and can stop partway through. Repeating the request\npicks up where it stopped, so clear whatever a refusal named and send it again.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete deployment"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.DeploymentsAPI.DeleteDeployment(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newDeploymentsGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <deployment_id>",
		Short: "Get a deployment",
		Long:  "Get one deployment. An AWS deployment includes the external id needed to register on it.\n\nAn id that does not exist, belongs to another account, or names a deployment on Monte\nCarlo's older collection platform all return 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.DeploymentsAPI.GetDeployment(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "type", "runtime_platform", "enabled", "aws_external_id")
		},
	}
	return cmd
}

func newDeploymentsListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List deployments",
		Long:  "List the deployments in your account.\n\nA deployment is the infrastructure that connects Monte Carlo to your environment. Each\none hosts a collection agent or a data store, or is hosted by Monte Carlo itself.\n\nOnly deployments on Monte Carlo's current collection platform are listed. Deployments on\nthe older platform are managed separately and do not appear here.\n\nDeployments are sorted by name, ignoring case.\n\nA deployment's external id is returned by the single-deployment read, not by this list.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.DeploymentsAPI.ListDeployments(ctx)
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderList(cmd, out, []string{"id", "name", "type", "runtime_platform", "enabled"})
		},
	}
	return cmd
}

func newDeploymentsReprovisionCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "reprovision <deployment_id>",
		Short: "Reprovision a deployment",
		Long:  "Give a deployment something fresh to register.\n\nUse this to recover a deployment whose collection agent or data store was deleted, and to\nchange what a deployment hosts. The deployment itself is kept, so it does not count\nagainst your account's limit a second time, and what it hosted is discarded. An AWS\ndeployment is given a new external id, so a role trust policy naming the old one has to be\nupdated.\n\nA deployment whose collection agent or data store is enabled cannot be reprovisioned;\ndelete that first. Neither can one hosted by Monte Carlo, which this API does not\nprovision.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Reprovision deployment"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.DeploymentsAPI.ReprovisionDeployment(ctx, args[0])
			typeValue, err := flagString(cmd, "type")
			if err != nil {
				return err
			}
			type_, err := sdk.NewDeploymentTypeFromValue(typeValue)
			if err != nil {
				return err
			}
			runtimePlatformValue, err := flagString(cmd, "runtime-platform")
			if err != nil {
				return err
			}
			runtimePlatform, err := sdk.NewRuntimePlatformFromValue(runtimePlatformValue)
			if err != nil {
				return err
			}
			body := sdk.NewDeploymentIn(*type_, *runtimePlatform)
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.DeploymentIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "type", "runtime_platform", "enabled", "created_time", "last_updated_time", "aws_external_id")
		},
	}
	cmd.Flags().String("type", "", "What the deployment will host. Only COLLECTION_AGENT and COLLECTION_DATA_STORE can be provisioned today. Any other value is rejected.")
	_ = cmd.RegisterFlagCompletionFunc("type", enumCompletion(sdk.AllowedDeploymentTypeEnumValues))
	_ = cmd.MarkFlagRequired("type")
	cmd.Flags().String("runtime-platform", "", "Where the deployment's collection agent or data store will run. Either can be provisioned on AWS, AZURE or GCP, and a collection agent also on GENERIC. Any other combination is rejected.")
	_ = cmd.RegisterFlagCompletionFunc("runtime-platform", enumCompletion(sdk.AllowedRuntimePlatformEnumValues))
	_ = cmd.MarkFlagRequired("runtime-platform")
	cmd.Flags().String("name", "", "Display name for the deployment. Monte Carlo generates one if you leave it out.")
	return cmd
}

func newDeploymentsUpdateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update <deployment_id>",
		Short: "Update a deployment",
		Long:  "Rename a deployment.\n\nThe name is the only thing you can change here. What a deployment hosts and where it runs\nare settled when it is provisioned, so use reprovision to change either.\n\nRenaming changes nothing about the infrastructure behind the deployment. Every deployment\ncan be renamed, including one hosted by Monte Carlo. Sending an empty body leaves the\ndeployment as it is and returns it.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.DeploymentsAPI.UpdateDeployment(ctx, args[0])
			body := sdk.NewDeploymentPatch()
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.DeploymentPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "type", "runtime_platform", "enabled", "created_time", "last_updated_time", "aws_external_id")
		},
	}
	cmd.Flags().String("name", "", "New display name for the deployment. Left out, the name is unchanged.")
	return cmd
}
