// Code generated by api-codegen; DO NOT EDIT.

package cmd

import (
	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newEtlContainersCmd())
}

func newEtlContainersCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "etl-containers",
		Short: "Etl containers",
	}
	cmd.AddCommand(newEtlContainersCreateCmd())
	cmd.AddCommand(newEtlContainersDeleteCmd())
	cmd.AddCommand(newEtlContainersGetCmd())
	cmd.AddCommand(newEtlContainersListCmd())
	cmd.AddCommand(newEtlContainersUpdateCmd())
	return cmd
}

func newEtlContainersCreateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create an ETL container",
		Long:  "Create an empty ETL container.\n\nThe container holds no connection until you add one. Its type is fixed at creation and\ndecides which connection it accepts. Every type except `airflow` runs through a\ndeployment, which has to be one the deployments list returns; any other id returns 404.\nA deployment that does not support the ETL tool, or needs an upgrade first, returns 409.\nA deployment takes one `fivetran` container. A name another container of the same type\nalready uses returns 409. A type your account's plan does not include returns 403.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.EtlContainersAPI.CreateEtlContainer(ctx)
			typeValue, err := flagString(cmd, "type")
			if err != nil {
				return err
			}
			type_, err := sdk.NewNewEtlContainerTypeFromValue(typeValue)
			if err != nil {
				return err
			}
			name, err := flagString(cmd, "name")
			if err != nil {
				return err
			}
			body := sdk.NewEtlContainerIn(*type_, name)
			if changed(cmd, "deployment-id") {
				deploymentId, err := flagString(cmd, "deployment-id")
				if err != nil {
					return err
				}
				body.SetDeploymentId(deploymentId)
			}
			req = req.EtlContainerIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "type", "name", "is_synthetic", "deployment_id", "deployment_name", "created_time")
		},
	}
	cmd.Flags().String("type", "", "The ETL tool the container represents. Its connection has to be for this tool. Cannot be changed after the container is created.")
	_ = cmd.RegisterFlagCompletionFunc("type", enumCompletion(sdk.AllowedNewEtlContainerTypeEnumValues))
	_ = cmd.MarkFlagRequired("type")
	cmd.Flags().String("name", "", "Display name for the ETL container. No two containers of the same type can share a name.")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().String("deployment-id", "", "The deployment the container's connection will run through. Pick one from the deployments list. Only a deployment on Monte Carlo's current collection platform is accepted. Required for every type except airflow, which takes none.")
	return cmd
}

func newEtlContainersDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <etl_container_id>",
		Short: "Delete an ETL container",
		Long:  "Delete an ETL container.\n\nOnly an empty container can be deleted. A connection is managed as its own resource and\nis never deleted with its container, so remove it first. A synthetic container cannot be\ndeleted here. Both refusals return 409.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete etl container"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.EtlContainersAPI.DeleteEtlContainer(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newEtlContainersGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <etl_container_id>",
		Short: "Get an ETL container",
		Long:  "Get one ETL container.\n\nAn id that does not exist or belongs to another account returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.EtlContainersAPI.GetEtlContainer(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "type", "name", "is_synthetic", "deployment_id", "deployment_name", "created_time")
		},
	}
	return cmd
}

func newEtlContainersListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List ETL containers",
		Long:  "List every ETL container in your account, oldest first.\n\nThe list includes synthetic containers, which this API does not create or delete.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.EtlContainersAPI.ListEtlContainers(ctx)
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderList(cmd, out, []string{"id", "name", "type", "is_synthetic", "deployment_name"})
		},
	}
	return cmd
}

func newEtlContainersUpdateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update <etl_container_id>",
		Short: "Update an ETL container",
		Long:  "Rename an ETL container.\n\nThe name is the only thing you can change. The type and the deployment are fixed when the\ncontainer is created. A name another container of the same type already uses returns 409.\nSending an empty body leaves the container as it is and returns it.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.EtlContainersAPI.UpdateEtlContainer(ctx, args[0])
			body := sdk.NewEtlContainerPatch()
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.EtlContainerPatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "type", "name", "is_synthetic", "deployment_id", "deployment_name", "created_time")
		},
	}
	cmd.Flags().String("name", "", "New display name for the ETL container. Omit it to leave the name unchanged. An explicit null is ignored, the same as omitting the field.")
	return cmd
}
