// Code generated by api-codegen; DO NOT EDIT.

package cmd

import (
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(newValidationsCmd())
}

func newValidationsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "validations",
		Short: "Validations",
	}
	cmd.AddCommand(newValidationsGetCmd())
	return cmd
}

func newValidationsGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get validation",
	}
	cmd.AddCommand(newValidationsGetRunCmd())
	return cmd
}

func newValidationsGetRunCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "run <run_id>",
		Short: "Get a validation run",
		Long:  "Read a validation run started by a validate operation.\n\nPoll this until `status` is `completed`. Each validation carries its own `status` and,\nonce it has one, a `passed` verdict with the problems behind it.\n\nA run is kept for a limited time after it starts and then forgotten. An id that has\nexpired, never existed, or belongs to another account all return 404.\n\n`Retry-After` says how long to wait before polling again.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.ValidationsAPI.GetValidationRun(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "status", "target_type", "target_id", "validations_passed", "validations_total", "started_at", "finished_at", "expires_at", "validations")
		},
	}
	return cmd
}
