// Code generated by api-codegen; DO NOT EDIT.
package cmd

import (
	"net/http"

	"github.com/spf13/cobra"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

func init() {
	rootCmd.AddCommand(newWarehousesCmd())
}

func newWarehousesCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "warehouses",
		Short: "Warehouses",
	}
	cmd.AddCommand(newWarehousesCreateCmd())
	cmd.AddCommand(newWarehousesDeleteCmd())
	cmd.AddCommand(newWarehousesGetCmd())
	cmd.AddCommand(newWarehousesListCmd())
	cmd.AddCommand(newWarehousesUpdateCmd())
	return cmd
}

func newWarehousesCreateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a warehouse",
		Long:  "Create an empty warehouse.\n\nThe warehouse holds no connections until you add some. Its type is fixed at creation and\ndecides which connections it accepts. The deployment has to be one the deployments list\nreturns; any other id returns 404.\n\nTwo warehouses of the same type cannot share a name.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.WarehousesAPI.CreateWarehouse(ctx)
			name, err := flagString(cmd, "name")
			if err != nil {
				return err
			}
			typeValue, err := flagString(cmd, "type")
			if err != nil {
				return err
			}
			type_, err := sdk.NewWarehouseTypeFromValue(typeValue)
			if err != nil {
				return err
			}
			deploymentId, err := flagString(cmd, "deployment-id")
			if err != nil {
				return err
			}
			body := sdk.NewWarehouseIn(name, *type_, deploymentId)
			req = req.WarehouseIn(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "type", "deployment_id", "created_time")
		},
	}
	cmd.Flags().String("name", "", "Display name for the warehouse. Unique among your warehouses of the same type.")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().String("type", "", "The kind of data platform the warehouse represents. Every connection added to it has to fit. Cannot be changed after the warehouse is created.")
	_ = cmd.RegisterFlagCompletionFunc("type", enumCompletion(sdk.AllowedWarehouseTypeEnumValues))
	_ = cmd.MarkFlagRequired("type")
	cmd.Flags().String("deployment-id", "", "The deployment the warehouse's connections will run through. Pick one from the deployments list. Only a deployment on Monte Carlo's current collection platform is accepted.")
	_ = cmd.MarkFlagRequired("deployment-id")
	return cmd
}

func newWarehousesDeleteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <warehouse_id>",
		Short: "Delete a warehouse",
		Long:  "Delete a warehouse.\n\nOnly an empty warehouse can be deleted: one that still has connections, or that other\nwarehouses consume from, is refused. Connections are managed as their own resources and\nare never deleted with a warehouse. Remove them first.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := confirm(cmd, "Delete warehouse"+" "+args[0]); err != nil {
				return err
			}
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.WarehousesAPI.DeleteWarehouse(ctx, args[0])
			if resp, err := req.Execute(); err != nil {
				return apiErr(resp, err)
			}
			return nil
		},
	}
	return cmd
}

func newWarehousesGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <warehouse_id>",
		Short: "Get a warehouse",
		Long:  "Get one warehouse.\n\nAn id that does not exist, belongs to another account, or names a warehouse your domain\nrestrictions hide from you returns 404.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.WarehousesAPI.GetWarehouse(ctx, args[0])
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "type", "deployment_id", "created_time")
		},
	}
	return cmd
}

func newWarehousesListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List warehouses",
		Long:  "List the warehouses in your account, a page at a time.\n\nWarehouses are returned oldest first. A caller whose asset access is restricted to\ncertain domains sees only the warehouses holding assets in those domains.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.WarehousesAPI.ListWarehouses(ctx)
			if changed(cmd, "cursor") {
				cursor, err := flagString(cmd, "cursor")
				if err != nil {
					return err
				}
				req = req.Cursor(cursor)
			}
			if changed(cmd, "limit") {
				limit, err := flagInt(cmd, "limit")
				if err != nil {
					return err
				}
				req = req.Limit(limit)
			}
			if changed(cmd, "with-count") {
				withCount, err := flagBool(cmd, "with-count")
				if err != nil {
					return err
				}
				req = req.WithCount(withCount)
			}
			if !changed(cmd, "cursor", "limit", "with-count") {
				return renderPages(cmd, []string{"id", "name", "type", "deployment_id"}, func(cursor string) (any, *http.Response, error) {
					r := req
					if cursor != "" {
						r = r.Cursor(cursor)
					}
					return r.Execute()
				})
			}
			out, resp, err := req.Execute()
			if err != nil {
				return apiErr(resp, err)
			}
			return renderPage(cmd, out, []string{"id", "name", "type", "deployment_id"})
		},
	}
	cmd.Flags().String("cursor", "", "Position to continue from, as returned in next_cursor by the previous page. Omit it to start from the first page. The value is opaque; do not build or modify one.")
	cmd.Flags().Int32("limit", 0, "Maximum number of items to return, between 1 and 100.")
	cmd.Flags().Bool("with-count", false, "Whether to also return the total number of items across every page, in count. Off by default: counting costs an extra query.")
	return cmd
}

func newWarehousesUpdateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update <warehouse_id>",
		Short: "Update a warehouse",
		Long:  "Rename a warehouse.\n\nThe name is the only thing you can change. The type and the deployment are fixed when\nthe warehouse is created. Two warehouses of the same type cannot share a name. Sending an\nempty body leaves the warehouse as it is and returns it.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			api, ctx, err := apiClient(cmd)
			if err != nil {
				return err
			}
			req := api.WarehousesAPI.UpdateWarehouse(ctx, args[0])
			body := sdk.NewWarehousePatch()
			if changed(cmd, "name") {
				name, err := flagString(cmd, "name")
				if err != nil {
					return err
				}
				body.SetName(name)
			}
			req = req.WarehousePatch(*body)
			out, resp, err := retryOnTransient(cmd, req.Execute)
			if err != nil {
				return apiErr(resp, err)
			}
			return render(cmd, out, "id", "name", "type", "deployment_id", "created_time")
		},
	}
	cmd.Flags().String("name", "", "New display name for the warehouse. Omit it to leave the name unchanged. An explicit null is ignored, the same as omitting the field.")
	return cmd
}
